### ISSUE TITLE
Problems setting up Frege with Intellij

### ISSUE THREAD

**Issue by codygman** [Frege/frege#105]
I was reading `Using Frege in Intellij IDEA` and I had no problem with step 1 (associate Frege with Haskell filetype).

> Next you need the Frege jar (and the REPL jars if you want to use it) as a library in IDEA.

Okay, hmm... where is the Frege jar? I looked on the Frege releases page and it wasn't there. I then figured out it was a separate project from browsing another page. Maybe you should provide a link here. (I don't mind submitting a pull request with these suggestions, time permitting... but wanted to get your thoughts).

> I recommend to create a "global" library such that you can share it between many projects. Note that you can point directly to your download locations of the jars

I didn't have much of an idea what or where this was being new to intellij, but the picture saved me and I noticed "Project Structure" and I'd been there once before.

> head over to https://github.com/Dierk/HelloFrege and download the project. (You can use your preferred method of either cloning, forking, or downloading as zip).

Done!

> You should now be able to open that project in IDEA. Most likely some of your local names are different from what the project expects, e.g. the name of the Java SDK and the names of the Frege and FregeRepl libraries. You need to adapt this in the project structure / module settings.

![1425020735](https://cloud.githubusercontent.com/assets/225847/6408589/f4886066-be1c-11e4-911e-ecfc50646795.png)

I would, but above you can see there are two things "HelloFrege" and "target" with similar contents... do I modify one, both, or... I don't have much confidence or context with frege projects yet.

> That being done, you can edit the Frege code with automatic compile, run all quickcheck tests and work with the REPL.
> 
> Rename the application, adapt the git settings, and add off you go with your own project!

Uh oh, I've done something wrong. I'm pretty sure I just need to rename these paths but I'm not sure how and I've used up the free time I had available  and ended up with this:

![1425020671](https://cloud.githubusercontent.com/assets/225847/6408604/36db85ba-be1d-11e4-84bb-765903a013e3.png)

Thanks for all your hard work on Frege, I hope this will help you make the "Getting Started" process a little smoother for people possible new to Java, Frege, Haskell, etc.

**Comment by Dierk** [comment]
Hi Codygman,

I should have been more explicit about the intended audience for that page: Java developers with a strong IntellijIdea bias :-)
The more surprising it is how far you have come given that you possibly don't have that background. 

What kind of programming have you done before?
What makes you coming to Frege?

In terms of smoothness, we are working on the gradle integration, which will supersede that respective page soon. 

All the best
Dierk

sent from:mobile

**Comment by codygman** [comment]
> What kind of programming have you done before?

I've done Python, (some) Java, Go, Racket, and Haskell programming before along with other usual suspects in web development.

> What makes you coming to Frege?

I've recently been using Java for android and moving towards Scala. I realized that Frege also had transparent Java interop and I could probably use it for android. Since I had just started using Android I have some small experience with Android Studio/Intellij Ultimate and saw your how-to page.

> In terms of smoothness, we are working on the gradle integration, which will supersede that respective page soon.

Cool!

**Comment by Dierk** [comment]
That is good to hear.

If you did some Haskell before, you will feel right at home.

Getting to know Intellj IDEA will certainly pay off for Android development as well.

Does that mean that you are targeting to create Android apps with Frege?

cheers
Dierk

**Comment by codygman** [comment]
Yes, I do plan to targeting android with Frege. Do you see any problems with that? I think there will be a large impedance mismatch due to the imperative nature of the Android API, but bindings could be made over the android api to be more idiomatic I think.

This is just an idea that has my attention currently, I won't know if I want to commit to it until I put some effort towards it ;)

**Comment by Dierk** [comment]
I think that the java files that frege emits should be perfectly fine for the android compiler.
I'd love to see the effort and get some experience if and how the purely functional approach can also bring its benefits to mobile and UI development!

Dierk

sent from:mobile

**Comment by Ingo60** [comment]
Is Android up to Java 7 yet? 

Otherwise we probably need some work being done on the Java 6 compatibility thing.

**Comment by codygman** [comment]
Looks like only Java 6 api is supported still:

http://stackoverflow.com/questions/15848332/does-adt-support-java-7-api

**Comment by Dierk** [comment]
wiki page clarified
