### ISSUE TITLE
build-instructions.md is not up to date: `frege.mk` target doesn't exist any more

### ISSUE THREAD

**Issue by tkawachi** [Frege/frege#107]
`build-instructions.md` says to run `make frege.mk`. but the target doesn't exist.

**Comment by Dierk** [comment]
cool to see the travis effort!

You best make sure that the build runs on your local machine first. 
It is quite involved and generates new make files and targets that are then executed.

**Comment by tkawachi** [comment]
I confirmed my pull request can build the compiler. see https://travis-ci.org/tkawachi/frege/builds/52424955.

Also, I observed it occasionally failed to compile on Oracle JDKs with same .travis.yml when arranging the commit. https://travis-ci.org/tkawachi/frege/builds/52424432.

Maybe better to comment on #106 ?

**Comment by tkawachi** [comment]
`frege.mk` itself seems to be removed at f731466b44a5c76805481fc392cab244c6e5d51c. Then I suppose it's no longer needed.

**Comment by Ingo60** [comment]
I must say I am a bit at odds with the build-instructions.md file:

- it is out of date (and misleading, as can be seen)
- it gives no generally useful info that is not in the getting started Wiki file. 
- I am not going to maintain 2 almost identical files, and it looks like Dierk doesn't either. 

I  therefore propose to remove it altogether. Rationale: he who wants to build the compiler should at least have read "Getting Started".

(Apple specific stuff should go in a separate Wiki page. But not in the top directory. It's simply not THAT important, even if you mc fans out there can't believe it. )

**Comment by Dierk** [comment]
I'd say that the convention in the open-source world is to find the build instruction in the project root dir. 
The very least would be to provide a pointer to the wiki page. I prefer the other way around though such that the build instructions are automatically versioned with the project state (reproducible builds).

Dierk

sent from:mobile

**Comment by Ingo60** [comment]
Well, then our opinions differ here, which is no drama as long as someone feels responsible for keeping it up to date (not me,  I'll maintain the Getting Started, if the need arises).

It still bugs me that my git pushs will fail when someone changes but a iota in that file. That is why I think that the separate wiki that github provides is advantageous.

**Comment by Dierk** [comment]
Kent Beck once told me "progress comes from the disagreement of friends" :-)

Dierk

sent from:mobile

**Comment by seancorfield** [comment]
FWIW, I don't think **Compiling the Compiler** belongs in **Getting Started** at all. *Getting Started* should tell new Frege _users_ how to write, compile, and run their own `.fr` files. Building Frege itself should definitely be a separate document somewhere -- and having it on the wiki would allow others to contribute to that documentation, to keep it up to date, and to explain other ways of building the system.

If *Compiling the Compiler* was moved to a *Contributing to Frege* page -- that explained how to build and test the compiler, as well as your preferred process for contributors to help with the project -- then the `build-instructions.md` could be just a pointer to the (new) *Contributing to Frege* page.

**Comment by Ingo60** [comment]
Dierk, I am quite happy that you see it that way.
I fully agree with Sean on how the things should get arranged. Let the words be followed by deeds, guys!
And in this way, we finally will have progress!

Meanwhile, I will see how I can make the "Getting Started" better, we have complaints there in Issue#104. In the moment I see the "Contributing ..." page appear, I will remove the "Compiling..." section there.

If the need arises later, I'll of course do my best to keep the "Contributing ..." page up to date. I only refuse to do such time consuming tasks on 2 files.

**Comment by Dierk** [comment]
New structure

https://github.com/Frege/frege/wiki/Contributing-to-Frege
https://github.com/Frege/frege/wiki/Getting-Started
https://github.com/Frege/frege/blob/master/build-instructions.md

cheers
Dierk

**Comment by tkawachi** [comment]
Thanks for updating the docs.
