### ISSUE TITLE
lang-ref "seamless"

### ISSUE THREAD

**Issue by Dierk** [Frege/frege#115]
Section 1.1 mentions "seamless access to Java".

This is true in the sense that we usually do not need any wrapper classes but we do have "seams" in the type system through the native declaration - and those are a main distinctive feature from languages that call into Java without any protection and thus lose their language guarantees when doing so.

I would avoid the word "seamless" altogether in any communication. It is misleading.

I would put this as "efficient & safe":
- access to Java that is efficient (no wrappers) but still typesafe in the Frege sense
- language guarantees are kept, e.g. there is no null in Frege. Java nulls occur as the Maybe type in Frege.

**Comment by Ingo60** [comment]
Fixed.
