### ISSUE TITLE
provide evalStateT and execStateT on StateT

### ISSUE THREAD

**Issue by Dierk** [Frege/frege#128]
analogous to https://www.haskell.org/hoogle/?hoogle=StateT

For State, the respective functions are there but not for StateT. This applies not only to the Haskell-friendly names. Also the to-be-aliased functions are missing.

Some examples would also be helpful.

**Comment by Ingo60** [comment]
I am not sure what you mean with "the to-be-aliased functions"?

Anyway, now we have runStateT, evalStateT and execStateT

**Comment by Dierk** [comment]
thanks! (and my wording was really bad - thinking of evalStateT as an alias for StateT.eval where it is really fst . StateT.run)
