### ISSUE TITLE
Unclear error message: looked for constructor undefined, found value `undefined`

### ISSUE THREAD

**Issue by mmhelloworld** [Frege/frege#134]
In the following code:

```frege
frege> bar = A {foo = 10}
3: can't resolve `A`, did you mean `$` perhaps?
3: looked for constructor undefined, found value `undefined`
```
The last error message is confusing. Since the first error message is already clear, I think we can just not show the second one or am I missing something?

**Comment by Ingo60** [comment]
Thanks for he hint, Marimuthu.
Fixed with aa55d2663090e30eb2602d774f4f403ee39eaae8
