### ISSUE TITLE
convenience alias "for"

### ISSUE THREAD

**Issue by Dierk** [Frege/frege#144]
we have a number of aliases to provide both a java-friendly and a haskell-friendly name, e.g. println and putStrLn.
I'd like to see "for" as an alias for "forM_" such that we can write
    for [1, 2, 3] println
which is more natural for the java developer.
An alternative would be to use "each".

**Comment by Ingo60** [comment]
Seems fair.

**Comment by Dierk** [comment]
fixed

**Comment by vendethiel** [comment]
I think there's a typo in the commit (`for`'s argument name)

**Comment by Dierk** [comment]
I made the name "lst" on purpose.
It is not fully a list or a collection but any listSource (we prefer short names, though).

**Comment by vendethiel** [comment]
Right, but `coll` is used inside the function

**Comment by Ingo60** [comment]
Travis CI is also complaining. 

I strongly suggest doing

    make test

**before** pushing to master.

**Comment by Dierk** [comment]
shoot!

Note to self: never assume a change is sooooo small...

**Comment by Dierk** [comment]
fixed. Sorry for the hassle and thanks a lot for the notice, Ven!

(BTW: used the slightly longer but more telling "listSource" parameter name)
