### ISSUE TITLE
file reader/writer convenience functions: Exception and parameter naming

### ISSUE THREAD

**Issue by Dierk** [Frege/frege#146]
I doubt that new File(string) throws FileNotFoundException :-)
https://github.com/Frege/frege/blob/master/frege/java/IO.fr#L255-255

Also openReader has a parameter called "file" which is not a File but a _file name_ and the writer functions have "name". I suggest to consistently use "fileName" in all cases.

**Comment by Ingo60** [comment]
You're right with `new File(...)`.

Regarding the parameter names - as ephemeral as they are - we could make it a habit to use the ones Java uses in their API. (Sometimes there will not be a direct match, but that's okay.)

But 1 line of documentation would still be better than 10 undocumented functions with "correct" parameter names, IMHO.

**Comment by Dierk** [comment]
agreed to use the JDK parameter names.

While I would say that a good parameter name is worth 10 lines of apidoc :-)

**Comment by Ingo60** [comment]
> a good parameter name is worth 10 lines of apidoc

The API doc you see, but the parameter names you don't see unless browsing the source code, but when you (need to) do that, it is an indication that the API doc is bad or just missing.

**Comment by Dierk** [comment]
Ah, true. 
That's a bit of a disadvantage to Java. 
BTW: Ruby has a nice feature where the docs can pop up the source code next to the method description...

Dierk

sent from:mobile

**Comment by Ingo60** [comment]
Haskell doc has this too.
I have no clue how they do that.

2015-04-21 22:30 GMT+02:00 Dierk König <notifications@github.com>:

**Comment by Ingo60** [comment]
This is apparently fixed for some time.
