### ISSUE TITLE
String to Number conversion

### ISSUE THREAD

**Issue by Dierk** [Frege/frege#147]
The current Prelude provides no means to read a number like 123 from a string like "123".

One solution would be to make Int, Integer, and Double instances of ReadS.

**Comment by mmhelloworld** [comment]
The conversion functions are already there in [PreludeBase](https://github.com/Frege/frege/blob/master/frege/prelude/PreludeBase.fr#L602).

```
frege> "23".int
:: (NumberFormatException | Int)

frege> either (const 0) id "23".int
23

frege> either (const 0) id "23".double
23.0

frege> either (const 0) id "23".integer
23
```

**Comment by Dierk** [comment]
ah - ok, thanks.

**Comment by Ingo60** [comment]
Yeah, this is a point we should stress in beginners tutorials.
I never felt easy with implementing read .... it is supposed to be a pure function, but as such you can't act on errors. But this is crucial, for example when you get something via the command-line.
