### ISSUE TITLE
compile time

### ISSUE THREAD

**Issue by s-trooper** [Frege/frege#149]
The compile time of "hello world" is about ~3 s on my machine vs Haskell < 1 s and java 400 ms for same. My question is what workflow one use for daily work in frege, just to endure this 3+ sec? I hope for existence of ghc-mod/sbt solution i not aware of :)

**Comment by Ingo60** [comment]
Congratulations, you have a fast machine! Mine needs almost six.

Seriously, the compiler is not quite suited for a traditional command-line edit-compile-run cycle. The reason being the JVM startup costs with that many thousand classes, whereas the marginal cost of compiling yet another additional definition is not noticeable. For example, while I need almost 6 seconds for examples/Welcome.fr (7 lines), it takes me only around 3 minutes (i.e. factor 30) for the whole compiler, which has more than 35.000 lines (i,e, factor 5000).

It is much better in the [eclipse plugin](https://github.com/Frege/eclipse-plugin), where the JIT-ted compiler doesn't go away, so you are penalized only once for using the JVM, as long as you keep eclipse open.
Your code will be continuously parsed and type checked while you type, and once you have no errors you just Ctrl+S and it will only then continue compilation to the end. And that will usually be faster than you can invoke the Run ... action. So this is the workflow I suggest. Besides, you have other advantages like semantic coloring, live documentation, go to definition (even for library functions), and so on. You simply can't do that in vim or emacs.

I also expect that things improve substantially with Java-8, where we can utilize the inbuild lambdas for our purpose. For one, this should reduce the number of classes substantially. I also heard that running Java8 lambdas is much faster (by a factor of 60) compared to pre-Java8 "Function" classes.

This is why I am currently writing the Java8 backend.

**Comment by Dierk** [comment]
My usual setup is calling a gradle script from inside IDEA. This usually takes less than a second with incremental development, which is good enough for me to do the classical cycle. 
The fastest response time is inside the FregeFX REPL or the online REPL, which is to my perception almost instantaneous. The first one is easier for to set up when trying to apply small changes to a larger code base.

**Comment by Ingo60** [comment]
Right, I forgot the REPL, as FX application, online  or command line as one prefers. It is  simply always there to try things out and get a response in time.

This is just another way to have a "warm" (JIT-ted) compiler hanging around.

**Comment by Dierk** [comment]
BTW I forgot to mention that Gradle also runs with a deamon and therefore has a warmed-up JVM, in which the Frege compiler can run.
