### ISSUE TITLE
Math.round of Infinity

### ISSUE THREAD

**Issue by Dierk** [Frege/frege#150]
inf = 1/0
    Math.round inf
yields

    9223372036854775807
while

    Math.floor
    Math.ceil
both yield `Infinity` as expected. I believe that `round` should also yield `Infinity`.

**Comment by Ingo60** [comment]
This is not possible, as `round`  is supposed to return a `Long`, whereas `ceil` and `floor` give a `Double`.

This also just replicates what the JRE does, which 

> Returns the closest long to the argument, with ties rounding up.

Arguably, the result, which is the greatest Long available, is "closest" to infinity.

**Comment by Dierk** [comment]
Ah, true. Ok
