### ISSUE TITLE
Allow more ways to use specialized Fork/Join thread pools

### ISSUE THREAD

**Issue by Dierk** [Frege/frege#156]
Currently, the fork/join thread pool can only be set once and for all users of class "Concurrent".
The proposal is to use _instances_ of class Concurrent that take a ForkJoinPool as a constructor argument. Per instance, the pool would be final, sparing the necessity to synchronize pool access.

We could still have a default Concurrent singleton for the standard pool setup.

This would allow code like `withPool x f` to execute f with a ForkJoinPool of size x when the calling code knows that a count of x such threads is best suited for the function at hand.

**Comment by Ingo60** [comment]
It is not entirely clear to me how this should work. For, `f` is certainly an expression that knows nothing about fork/join pools?

The current implementation rests on the principle that programs not using `par`  or `forkIO` will never get penalized by creation of a forkjoin pool or an executor service pool. I'd very much like to keep it that way, given the already high JVM startup costs.

**Comment by Dierk** [comment]
I just found that there is anyway a predefined pool called "common" in the JDK ForkJoin class that gets created at class initialization time (with #processors - 1 but one can change that through a System property). That common pool is used by default for Java 8 parallelStreams.

We could use that in replacement of the pool that gets lazily created in the Concurrent class, thus avoiding creation of another object and the extra hit by synchronized.

The `withPool` idea would be an extra issue that only creates a new, parameterized pool (or allow the reuse of an existing pool) when `withPool` is explicitly called by a Frege application. This, again, would not need any synchronization at construction time.

The logical extension of this would be to remove the current ways of changing the lazily created singleton pool since that mechanism would be superseded. But this last step would be a breaking API change (Concurrent is public, whereas I think it can be made protected and thus removed from the public API at all).

**Comment by Ingo60** [comment]
Yeah, morally, all Runtime classes should be non-publi, that is: their API not directly exposed.

**Comment by Dierk** [comment]
The general idea follows the GPars construction (without the DSL part) under https://github.com/GPars/GPars/blob/master/src/main/groovy/groovyx/gpars/GParsPool.groovy#L142-142 , i.e. the pool is created or set to use before `f` is called and stopped afterwards. That means that whoever does not want to use the common default ForkJoin pool, can create his private one, tailored to his own needs.

We may want to have two variants:

    withPoolSized n f ... -- create a fj pool of size n
    withPool pool f   ... -- reuse existing pool

I'm not quite sure, though whether such a construction works well in the context of lazy evaluation.

**Comment by vsts** [comment]
Hello,

I have thought about this idea and can think of it like here:

```haskell
--pooledAction :: Pool α
pooledAction :: Pool Int
pooledAction = do
    x <- fork(computationA)
    y <- fork(computationB)
    return (x + y)

withPoolSized 1 pooledAction
```
Where 
```haskell
withPoolSized :: Int -> ForkJoinPool α -> α
withPoolSized n f = evalPool f $ JForkJoinPool.new n
```
and `Pool` is is in fact a State Monad: `type Pool α = State JForkJoinPool α`. Thus the Pool is bound to the Monad but can be obtained by `evalPool` (`evalState`). Maybe this is misplaced as I do not know if `JForkJoinPool` could be seen as a pure value; my guess is no.

Does this reflect your thoughts, Dierk?

Greetings
  Volker

**Comment by Dierk** [comment]
Cool. That is exactly along the lines that I had in mind. I assume that return does an implicit join? Otherwise we could add such a function. More options could be working with an executor service.  
Moreover, other kinds of pools could profit from the same pattern using other capabilities than fork/join. 
Thanks! Dierk

**Comment by Ingo60** [comment]
@Dierk @vsts what is the state of this issue?

**Comment by Dierk** [comment]
I think @vsts has an impl on his private branch

**Comment by vsts** [comment]
Back then I did a dirty hack on this topic. But nothing serious.
The question of types came up: Is this a ST case as the thread pool does change over time? But there are no visible side effects involved as the computations are pure, just like when using `par`.
The F/J pool also may throw a
>  `RejectedExecutionException` - if the task cannot be scheduled for execution
on `submit`. But `par` does not care either …

**Comment by Ingo60** [comment]
Well, creating and maintaining a pool would certainly be ST. That doesn't mean *using* it (implicitly) would have to be.

But, to be honest, I am not really fond of thinking about this further, because in my opinion it goes counter the intuition of the FJ-pool to create and destroy them all the time. Rather, just like multi-core-CPUs, it should be just there when you need it. It is computing infrastructure, not something you should care about as parallel programmer. Maybe I'm wrong, but this is perhaps also the reason I don't really like this proposal.

For example, I don't see how

    withPool 4 x

on a 8 core machine does any good? Or

    withPool 129 x

on a 4 core machine?
Is it not so that you have N cores, and thus you can get parallelism N in the ideal case? So please, fork your tasks and let the runtime system care about it.

Needless to say, it is different with executor service pools, of course. That is why they are fed with IO actions, not pure computations.

**Comment by zjhmale** [comment]
what is `ST` stand for exactly? @Ingo60 @vsts

**Comment by Ingo60** [comment]
@zjhmale the data type `ST` used to compose stateful or I/O actions.

**Comment by zjhmale** [comment]
:ok_hand:

**Comment by Dierk** [comment]
The question is whether fork/join should only be there for computationally bound parallelism or also
for IO-bound concurrency. 
In Java, it is also often used for the latter where in Frege, we may not want to support that (?)

When IO-bound, it makes sense to use a specialized pool size, e.g. 10-12 threads to fetch web pages,
like most browsers do - no matter how many processors the machine has.

The logic of map/filter/reduce were e.g. fetching a page is the mapping step fits quite well to the
idea of fork/join but can of course also be achieved with other means.

**Comment by Ingo60** [comment]
We support concurrency (as opposed to parallelism) with `forkIO` which uses the executor services.

Here, I can see that providing a custom made executor service would make sense. Currently, only the one predefined in the runtime is used.

**Comment by vsts** [comment]
Indeed this should be of minor interest to Fork/Join pools.
Regarding `forkIO` this could be very useful as one might block all threads in the executor service by accident. I stumbled into this issue while porting the ant colony simulation from Rich Hickey. The ant agents are blocking the thread using `sleep`. I switched to `forkOS` to avoid this issue.
Clojure seems to provide two thread pools for agents. One pool of fixed size and one of variable size. One can send actions to an agent with `send` and `send-off` to supply the corresponding pool.

**Comment by Ingo60** [comment]
It's time to come to a conclusion.

I want to make it clear that the existing API for parallel/concurrent things (i.,e. `par`, `forkIO`, `forkOS`) are not to be changed (due to Haskell compatibility). I also think that the fork-join pool is the natural implementation for `par` (pure, parallel computations) and the executor service facility for `forkIO` (it doesn't **have** to be a fixed pool, though).

OTOH, I can imagine that @Dierk s proposal can be implemented easily on top of ExecutorService and Runnable or whatever is needed. It is ok to add this new API to `Control.Concurrent`. But please do it, anybody, or leave it as is, but get this old Issue closed soon.

I add this as a ToDo in project Libraries.

**Comment by Dierk** [comment]
For parallel computations, the default fork-join pool should be ok as these are typically CPU-bound computations.

For concurrent operations, it is often needed to specify the number of threads in the pool as this is not CPU- but IO-bound. Think about downloading files concurrently. Depending on the use case, but independent of the available CPU cores, one might want to download 10 files concurrently.
In cases like "anthill" one might want to have a pool of size 100.

Setting this "from the outside" may be possible but as good as I can foresee it at the moment still requires that the implementation (i.e. forkIO) can be parameterized with a pool.

**Comment by Ingo60** [comment]
Nope, you'll need to have something like forkPool. As I explained, we can't change the forkIO type signature. We can't allow overwriting the default pool either, or at most once for initialization,  as far as I can see.

**Comment by Dierk** [comment]
I’m ok with closing the issue.
