### ISSUE TITLE
Operator precedence of - (minus) does not work as expected

### ISSUE THREAD

**Issue by vsts** [Frege/frege#158]
Hi,

seems like operator precedence of `- :: Num n -> n -> n -> n` is broken:
```haskell
> 1 - 0 * 0
0
> 1 + 1 * 0
1
```
This happens to me in the REPL
```
$ frege-repl
Welcome to Frege 3.22.367-g2737683 (Oracle Corporation Java HotSpot(TM) 64-Bit Server VM, 1.8.0_45)
```
and with self compiled Frege in version `3.23.266-g353cc92`.
But `:help -` in the REPL says `infixl  13`.

Regards
  Volker

**Comment by Ingo60** [comment]
Indeed. Thank you for reporting.

This one caused me some headaches. But finally it turned out that it was caused by a precedence problem in the yacc code.
