### ISSUE TITLE
Feature Request: openjdk 1.6 for android

### ISSUE THREAD

**Issue by jimcrayne** [Frege/frege#159]
It would be very very nice if frege supported the same version of java required for android development, including older android releases going back to 2.2.

Android development, typically targets openjdk 1.6, which is compatible to java 6, and supplied tools compile that jvm code to dalvik byte code.

How difficult is it to backport frege to be compatible? If it is not a lot of work, it is definitely worth it, imo.

**Comment by ForNeVeR** [comment]
I think there was a standard feature to compile at least Java 7 code (with all or almost all features) to Android dex binary. What would you say?

**Comment by Ingo60** [comment]
It should not be difficult at all, as outlined in the [FAQ](https://github.com/Frege/frege/wiki/Frequently-Asked-Questions).

Some modifications and adaptions in the runtime (i.e. Concurrent.java6) may be needed, as the `fregec6.jar` target hasn't been maintained for a while. 

Also, you may want to include a backport of the fork/join API. If you don't you cannot use `frege.lib.ForkJoin` 

I leave this issue open for contributors who are willing to care about JDK 6 compatibility.
