### ISSUE TITLE
Compiler generates illegal Java code for a datatype involving explicit forall

### ISSUE THREAD

**Issue by danielkroeni** [Frege/frege#160]
The Frege compiler generates invalid Java code for the following data type:
```data Showable = S { s :: (forall a. Show a => a) }```

Fix: Preferably add support for existentials or let the Frege compiler reject the definition.

Here is the full story:
```
cortex:frege dk$ cat test.fr 
module Test where
data Showable = S { s :: (forall a. Show a => a) }

cortex:frege dk$ java -Xss2m -jar frege3.22.524-gcc99d7e.jar test.fr 
calling: javac -cp frege3.22.524-gcc99d7e.jar:. -d . -sourcepath . -encoding UTF-8 ./Test.java 
./Test.java:177: error: cannot find symbol
    return frege.runtime.Delayed.<java.lang.Object>forced(arg$1.apply(ctx$1).result());
                                                               ^
  symbol:   method apply(CShow)
  location: variable arg$1 of type Object
1 error
E test.fr:3: java compiler errors are most likely caused by erronous
    native definitions
runtime 2.736 wallclock seconds.
```

The generated compiler error message contains a typo in the word "erronous".

**Comment by Ingo60** [comment]
The above type should not be accepted by the compiler and no code should be generated at all.

It must be noted that the following is accepted, though the type is nonsensical:

    ingo@freguntu:~$ frepl
    Welcome to Frege 3.22.367-g2737683 (Oracle Corporation OpenJDK 64-Bit Server VM, 1.7.0_79)
    
    frege> data W = Uh (forall a.a)
    data type W :: *

    frege> foo f = case f of Uh noes -> (noes, noes)
    function foo :: W -> (a,b)

    frege> foo (Uh ())
    [ERROR: 5]: E <console>.fr:5: type `()` is not as polymorphic as suggested in the
        annotation where just `a` is announced.
    [HINT: 5]: H <console>.fr:5: The inferred type must be at least as polymorphic as
        the annotated one.
    [ERROR: 5]: E <console>.fr:5: type error in  expression ()
        type is   ()
        used as   a

That is, you cannot create a value of type `W`, except by using bottom:

    frege> foo (Uh undefined)
    :: (a,b)

    frege> foo (Uh undefined) :: (Int, Int)
    frege.runtime.Undefined: undefined

I think this behaviour is correct.
OTOH, you *can* have fields that are constrained **functions**:

    frege> data Good = Yeah () (forall a.Show a => (a,a) -> String)
    data type Good :: *

    frege> good = Yeah () (\x -> show (fst x) ++ show (snd x))
    function good :: Good

    frege> case good of Yeah _ f -> (f (0,42), f (false,true))
    ("042", "falsetrue")

So the fix for this bug would be to check that the constrained forall-type of a field is indeed a function type and reject it if this isn't so.

(Existential types are a different story.)

**Comment by danielkroeni** [comment]
You are absolutely right. This has nothing to do with existentials. I was confusing
```(forall a. Show a => a) -> Showable``` with ```forall a. Show a => a -> Showable```
The former type really requires a fully polymorphic argument which can only be bottom.

Now I think Frege should accept the original type definition ```data Showable = S { s :: (forall a. Show a => a) }``` and generate code which takes into account that the argument can only be bottom.

This would be consistent with Haskell:
```
Prelude> :set -XRankNTypes
Prelude> data Showable = S (forall a. Show a => a)
data Showable = S (forall a. Show a => a)
Prelude> :t S
S :: (forall a. Show a => a) -> Showable
```

Just for completeness: This is the existential type is was looking for:
```
Prelude> :set -XExistentialQuantification
Prelude> data Showable = forall a. Show a => S a
data Showable where
  S :: Show a => a -> Showable
Prelude> let ss = [S (), S "x"] :: [Showable]
ss :: [Showable]
```

**Comment by Ingo60** [comment]
Java code is now correct, however, as stated before, no value of such a type can be created.
