### ISSUE TITLE
No obvious mention of language.pdf and implementation.pdf

### ISSUE THREAD

**Issue by xoltar** [Frege/frege#163]
Reasonably current versions of Language.pdf and Implementation.pdf should be prominently linked from the landing page. It took me hours to stumble on them.

**Comment by Dierk** [comment]
The language reference is linked from
https://github.com/Frege/frege#links

Any suggestions where they should rather go?

**Comment by xoltar** [comment]
That's fine, but it's way down at the bottom of a page that has lots of information I don't need as a newbie.  I'd love to see the landing page trimmed a bit. In the mean time, I'll add some additional pointers from the Getting Started page, which is where I was looking for them. I'll add a separate Documentation page on the wiki as well, which was the other thing

**Comment by xoltar** [comment]
Actually I'm thinking of moving Links, Contact, and Documentation information from the front page README to separate pages on the wiki, with links from README instead of content there. Too much?

**Comment by mperry** [comment]
Should we have a sidebar github wiki like https://github.com/guard/guard/wiki so that the wiki is organised like a website?  I had this problem too when looking for reference documentation.

**Comment by mperry** [comment]
I don't think I have see the Implementation.pdf file.  Do we have a link to that somewhere?  I wonder if there is other doc or info that should be retrieved from the old website.  From memory, I quite liked the old website.

**Comment by mperry** [comment]
I have added nearly all the info on the front readme to the wiki and linked using the sidebar to spoof a table of contents.

**Comment by mperry** [comment]
We need to think about the balance of how much information to put on the front readme that gets displayed on the Github project page and the information in the wiki.  How much duplication do we want?

@xoltar, does the "Language and API reference" link in the sidebar (https://github.com/Frege/frege/wiki/Language-and-API-Reference) serve your purposes?  If so, this issue can be closed.
