### ISSUE TITLE
make fails for docs

### ISSUE THREAD

**Issue by xoltar** [Frege/frege#164]
Maybe it's just me, but on my Ubuntu 14.04:

> $ make                                                                                                    [±master]
> latex -interaction batchmode  Language.tex
> This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
>  restricted \write18 enabled.
> entering extended mode
> make: **\* [Language.dvi] Error 1

However, "pdflatex Language.tex" works just fine...

**Comment by Ingo60** [comment]
Well, what can I say?
That damn latex thing is a mess. It works with one installation (i.e. MikTeX), but not with another.

Do you think it would be better to remove the Makefile and other unused files? So everyone would just see that he's on its own building this.

**Comment by xoltar** [comment]
That would be fine as long as the readme says something like "somehow compile Language.tex and/or Implementation.tex using whatever texy tools work on your system." Without the Makefile I wouldn't have known which file to call pdflatex on.

**Comment by Ingo60** [comment]
Yes, I see. I used to `make` things, but switched OS's/computers quite some times, and ended up using TeXstudio, which I somehow managed to  persuade that it should make the PDF.

I guess I should do some cleanup :)
