### ISSUE TITLE
default module name

### ISSUE THREAD

**Issue by mcandre** [Frege/frege#171]
Could frege attempt to infer the module name from the basename, like GHC does? E.g., `Hello.hs` would assume module name `Hello` unless an explicit module name was used.

**Comment by Ingo60** [comment]
Yes, this is certainly a good idea. 
We should take this into account when we implement the "program without module declaration" feature.

**Comment by mperry** [comment]
Are all the unimplemented features in github to browse?

**Comment by Ingo60** [comment]
@mperry I'm afraid no, they aren't yet. They exist only in the form of slides of my talk on Frege Day.

**Comment by Ingo60** [comment]
Implemented with aa20b6f43bae16ad07fc9a1dee11ceca7195e026

At the time being, and according to Haskell 2010 Standard, the module name will be `Main`
