### ISSUE TITLE
Classpath issues

### ISSUE THREAD

**Issue by mcandre** [Frege/frege#173]
I installed Frege via Homebrew, and used the `fregec` program to compile `HelloWorld.hs` to the respective `HelloWorld.class` files. But when I try to run `java HelloWorld`, Java complains that it can't find the Frege standard library classes. How can we make it easier for newbies to run their Frege programs?

* [ ] Offer a `frege` program that can run classes/JARs, and already has the Frege JAR in its classpath. This is how other altJVM languages like Groovy, Jython, JRuby, and Scala work.
* [ ] Offer build tool plugins for integrating Frege sources into JVM projects. Focus on Maven, Ant, SBT, and Gradle.

**Comment by Ingo60** [comment]
Here the same comments apply. If you use "homebrew" (I suspect some Apple centric redistribution of OSS) you're on your own. 

In the README it is detailed how the build tool support is. 

In short: Maven, Leiningen, SBT and Gradle are supported.
