### ISSUE TITLE
Backend for editors like ghc-mod

### ISSUE THREAD

**Issue by t3476** [Frege/frege#185]
Is there any plan for this? Eclipse is not my used editors

**Comment by Ingo60** [comment]
I think you mean an official compiler API.

No, it's not planned yet.

That being said, the eclipse plugin and the diverse REPLs use the compiler nevertheless.
From my experience with the eclipse-plugin I can tell that it is not too much. However, the editor must be capable  of interfacing the JVM. 

For editors that do not run themselves in the JVM, I guess one would need a local server that implements a protocol which allows to operate the compiler.

As in many other cases, for such an undertaking we'd need dedicated contributors. 
Maybe you want to take it on?

**Comment by Dierk** [comment]
Is that connected to the JSR 223 impl for Frege?

**Comment by Ingo60** [comment]
@Dierk well, not quite, I think.

This JSR is a way to run frege code snippets via some scripting engine from Java.
This is certainly not the way you would interface an editor/IDE/REPL with the compiler.
Correct me if I'm wrong, but the scripts that are run this way are themselves Frege-compiled. I'm not sure they are compiled  **each time** or whether there is some caching at work..

**Comment by Dierk** [comment]
Ok, thanks. 
JSR 223 has facilities to cache compilations but they lack a lot of features - esp. security. It has been designed for JavaScript...
