### ISSUE TITLE
maven repos

### ISSUE THREAD

**Issue by zjhmale** [Frege/frege#187]
i found two maven repos

* [repo1](https://repo1.maven.org/maven2/com/theoryinpractise/frege/frege/)
* [repo2](https://repo1.maven.org/maven2/org/frege-lang/frege/)

and is the first one deprecated now?

**Comment by mperry** [comment]
Repo 1 is obsolete (it used the group com.theoryinpractise.frege).  The project started using the group org.frege-lang to publish artifacts as per repo 2.

**Comment by mperry** [comment]
@zjhmale Do you require the frege jar or should you consider the various build tools available?

**Comment by zjhmale** [comment]
i just require the frege jar and repo2 is fine

**Comment by talios** [comment]
On 8 Oct 2015, at 18:46, λ . λ wrote:

> i found two maven repos
>
> * [repo1](https://repo1.maven.org/maven2/com/theoryinpractise/frege/frege/)
> * [repo2](https://repo1.maven.org/maven2/org/frege-lang/frege/)
>
> and is the first one deprecated now?

yes it is, but maven central is immutable and so can't be removed.

-- 
Mark Derricutt
http://www.theoryinpractice.net
http://www.chaliceofblood.net
http://plus.google.com/+MarkDerricutt
http://twitter.com/talios
http://facebook.com/mderricutt

**Comment by zjhmale** [comment]
:ok_hand: @talios
