### ISSUE TITLE
Strange syntax errors on instance declaration

### ISSUE THREAD

**Issue by muhuk** [Frege/frege#194]
I'm having this issue after upgrading to `3.23.370.b`. I've checked the docs and it seems this syntax is allowed. I couldn't find anything to decipher the error messages though. (I found #25 )

This is my class:

    class ToEDN a where
        toEDN :: a -> Value
        toEDN x = case toEDNtagged x of
           (Tagged _ y) -> y
           (NoTag y) -> y
    
        toEDNtagged :: a -> TaggedValue
        toEDNtagged = NoTag • toEDN

And this is the instance failing to compile:

    instance ToEDN (ToEDN a) => (Maybe a) where
        toEDN Nothing = Nil
        toEDN (Just a) = toEDN a

I get these errors:

    syntax error on ';'	EDN.fr	/frege-edn/src/frege/com/muhuk	line 27	Frege Problem
    syntax error, a sequence of one or more ',' cannot start with   token "Maybe"	EDN.fr	/frege-edn/src/frege/com/muhuk	line 25	Frege Problem
    syntax error, declarations local to a class, instance or type   cannot start with token "Nothing"	EDN.fr	/frege-edn/src/frege/com/muhuk	line 26	Frege Problem
    unexpected token "where" while trying to parse instance head	EDN.fr	/frege-edn/src/frege/com/muhuk	line 25	Frege Problem

Line 25 is the one that starts with `instance ToEDN`.

This instance compiles:

    instance ToEDN String where
        toEDN s = (String s)

**Comment by Ingo60** [comment]
Hi @muhuk, you are right, it used to be so, but now we switched to Haskell syntax, as announced [here](https://groups.google.com/forum/#!topic/frege-programming-language/-ndhQO7wAmc).

This is all part of a bigger plan, as agreed upon at the Frege day in Basel, to eradicate the "insignificant differences" (as Simon Peyton-Jones called it) to Haskell. See also the slides to get an idea of the yet outstanding changes: https://drive.google.com/open?id=1wdvP70ziDRaGZiKI3Zqb0ciLir4_axOH04APxaRtIsY

Meanwhile, I'm in the process of refreshing the lang ref, where the old syntax is still announced.

Please read the [release notes](https://github.com/Frege/frege/wiki/New-or-Changed-Features)

**Comment by muhuk** [comment]
Thanks, I was indeed looking at the language reference.

**Comment by Ingo60** [comment]
You'll also find, that the online frege docs show the new syntax.
And eclipse does this also in the hover docs and the outline view.
