### ISSUE TITLE
Module with `main` which only calls one user defined I/O action does not compile.

### ISSUE THREAD

**Issue by vsts** [Frege/frege#201]
The following file (`MainIssue.fr`) does not compile:

~~~
module MainIssue where

somefun = println "renamed main?"

main = do
    somefun
~~~

When compiling we get `cannot find symbol` error on `main`:

~~~
> fregec MainIssue.fr 
calling: javac -cp ~/Frege/frege/fregec.jar:build -d build -sourcepath . -encoding UTF-8 build/MainIssue.java 
build/MainIssue.java:89: error: cannot find symbol
        MainIssue._main)));
                 ^
  symbol:   variable _main
  location: class MainIssue
1 error
E MainIssue.fr:6: java compiler errors are most likely caused by
    erroneous native definitions
~~~

It works works fine with `main args = do somefun`.

> This is because "do {expr}" is syntactically flattened to expr and when expr is just a name, then main is just an alias for `somefun` and no code is generated for it.
> We shouldn't do this for main.

Regards
  Volker

**Comment by Ingo60** [comment]
This is now working so that the compiler generated main method runs whatever main is aliased to. The above code, for example, compiles to following main method:

    public static void main(final java.lang.String[] argv) {
      try {
        frege.run.RunTM.argv = argv;
        PreludeBase.TST.<Short>performUnsafe(somefun.call()).call();
      } finally { frege.run8.Concurrent.shutDownIfExists(); }
    }
