### ISSUE TITLE
Doesn't terminate with take on infinite list

### ISSUE THREAD

**Issue by wires** [Frege/frege#205]
So take this function `indexSt`, which returns all the indices of an array such that some condition holds on their elements.

```haskell
module foo.Bar where 

-- find the indices such that the conditions hold for it
indexSt :: (a -> Bool) -> [a] -> [Int]
indexSt cond xs = f x
  where
	p :: [Int]
	p = [1 .. length xs]

	q :: [Bool]
	q = map cond xs

	f = map fst . filter snd
	x = zip p q
```
So this prints `[2,4,5,6,7]` and terminates

    main = println . show $ indexSt even [1,2,3,4,4,4,4]

But this doesn't terminate

    main = println . show $ take 10 $ indexSt even [1..]

Compiled and ran using this:

    $ java -jar frege3.23.365-g185c1b5.jar -d build/ isItABug.fr
    calling: javac -cp frege3.23.365-g185c1b5.jar:build/ -d build/ -sourcepath . -encoding UTF-8 build//foo/Bar.java
    runtime 8.215 wallclock seconds
    $ java -cp frege3.23.365-g185c1b5.jar:build foo.Bar

Is this a bug?

**Comment by Dierk** [comment]
Hi Jelle,

well, the misconception lies in 

> p :: [Int]
>     p = [ 1 .. length xs]

where xs is the infinite list "even [1..]"
and length of an infinite list just takes infinitely long to calculate.

Using "take" on the result of "zip p q" does not prevent "length xs" from being evaluated.

If I see it correctly, you can achieve the desired effect by just using
  p = xs

happy coding
Dierk

**Comment by Ingo60** [comment]
Why not simply

    p = [1..]    -- do we care whether it is not longer? No!

(That would have been a nice SO question, BTW).

**Comment by wires** [comment]
Ah, of course, thanks!  And @Dierk, happy coding for sure: I've been complaining for years about not having Haskell on JVM and it seems that Frege is delivering. Very cool, very happy :hamburger:

(somehow this message stayed for nine days open in a browser tab... sorry!)
