### ISSUE TITLE
function as `infix` operator does not parse correctly if name contains an apostrophe

### ISSUE THREAD

**Issue by danielkroeni** [Frege/frege#210]
This compiles in Haskell:
```
f' :: a -> a -> a
f' a b = a

main = putStrLn $ "Hi" `f'` "ignore"
```
Here is what fregec says:
```
unexpected error token f' while trying to
    parse unary expression
```

**Comment by danielkroeni** [comment]
Here is the fix: https://github.com/Frege/frege/pull/211

**Comment by Ingo60** [comment]
Well, one always overlooks something.

But we must still take care that no true operator may have apostrophes, or at least not start with an apostrophe.

**Comment by Ingo60** [comment]
Merged.
