### ISSUE TITLE
Build steps fail at make fetch-fregec.jar

### ISSUE THREAD

**Issue by seancorfield** [Frege/frege#220]
```
> make fetch-fregec.jar
curl -H 'Accept: application/vnd.github.v3.raw' -kL -o fregec.jar `grep curl .travis.yml | 
  sed 's/.*https:/https/'`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: https
make: *** [fetch-fregec.jar] Error 6
```
Looks like the `sed` should be `s/.*https:/http:/` perhaps?

**Comment by seancorfield** [comment]
Changing that one line in the `Makefile` seems to get things working again.

**Comment by Ingo60** [comment]
Many thanks, Sean.

**Comment by seancorfield** [comment]
When I saw this was closed, I assumed the change was made in the repo but that doesn't appear to be the case so I think this should stay open until it is fixed (but I'm happy to commit a fix for it if I have permission).

**Comment by seancorfield** [comment]
Looks like I had permission! Fixed now.

**Comment by Ingo60** [comment]
Sorry for the confusion - I knew you had permission, so I didn't even bother to check for an actual  commit  :)
