### ISSUE TITLE
Library: Data.List -- Review for completeness / compatibility

### ISSUE THREAD

**Issue by seancorfield** [Frege/frege#231]
One of a series of placeholder issues based on Ingo's presentation about Haskell/Frege differences.

**Comment by vijaykiran** [comment]
* Different behaviour compared to GHC Data.List
```
frege> splitAt (-1) [1,2,3]
([1, 2, 3], [])

Prelude Data.List> splitAt (-1) [1,2,3]
([],[1,2,3])

frege> drop (-1) [1,2] == [1,2]
false

Prelude Data.List> drop (-1) [1,2] == [1,2]
True

frege> take (-1) [1,2] == []
false

Prelude Data.List> take (-1) [1,2] == []
True
```
 Missing functions
- `dropWhileEnd`
- `isSubsequenceOf`
- `scanl'`
- `sortOn`

**Comment by Ingo60** [comment]
@vijaykiran is on charge here

**Comment by vijaykiran** [comment]
WIP: https://github.com/vijaykiran/frege/commit/142ca567c2e089ea8b5cd4282f832c8a64786748

**Comment by mchav** [comment]
Was work on this completed?

**Comment by seancorfield** [comment]
Closing due to lack of feedback/interest.
