### ISSUE TITLE
Haskell way of getting processor count

### ISSUE THREAD

**Issue by russel** [Frege/frege#237]
The start point is almost certainly GHC specific, so may not be something to realize, but there needs to be a standard Frege idiom.

Using GHC, one can do things like:
```
import GHC.Conc (numCapabilities)
``` 
then:
```
putStrLn ("\tprocessor count = " ++ show numCapabilities)
```

This currently fails in Frege though one can do:
```
native availableProcessors "java.lang.Runtime.getRuntime().availableProcessors()" :: Int
```
and then:
```
putStrLn ("\tprocessor count = " ++ show availableProcessors)
```

**Comment by seancorfield** [comment]
We could make this easier by exposing Runtime in frege.java.Lang -- we already expose System in there. @Ingo60 your thoughts on that?

As for GHC.Conc itself, there's a lot of stuff in there that won't fit the JVM (or can't even be approximated) so it doesn't seem worth even creating a stub with `getNumProcessors` and the few other things that maybe _could_ be implemented.

**Comment by russel** [comment]
Given that System is exposed, and that Runtime used to be exposed, I think the thing to do here is to allow Runtime, or an instance of it, to be exposed again.

Given GHC.Conc is GHC it isn't really Haskell per se, so there are strong arguments for not trying to support that in Frege.

**Comment by seancorfield** [comment]
See #239 for discussion but the upshot is that as of 3.23.437 you can use:

* `System.availableProcessors ()`
* `System.freeMemory ()`
* `System.maxMemory ()`
* `System.totalMemory ()`

According to the Java docs, three of these can vary during the lifetime of the environment so we made all of them `() -> IO Long` (well, `availableProcessors` is `() -> IO Int`).

**Comment by russel** [comment]
Is there a standard way of making use of these snapshot releases? To date I have just used whatever is the latest formal release.

**Comment by seancorfield** [comment]
I'll be documenting that once I have the process a bit more streamlined. The TL;DR is:

* Add the Sonatype snapshots repository URI to your build tool's config
* Depend on 3.23.442-SNAPSHOT (current, most recent one)

On Gitter I just discussed some of the pros and cons of perhaps moving to 3.24-SNAPSHOT for all such prerelease builds (but right now I'd like to keep Frege versions and the Leiningen plugin/template versions in lock step to avoid confusion).

**Comment by Ingo60** [comment]
Looks like this can be closed also.

**Comment by russel** [comment]
Running on Debian Sid with JDK9 114, Frege 3.24.61, if I have the line:

native availableProcessors "java.lang.Runtime.getRuntime().availableProcessors()" :: Int

then I can do:

putStrLn ("\tprocessor count = " ++ show availableProcessors)

and everything works. However if I try:

putStrLn ("\tprocessor count = " ++ show System.availableProcessors)

I get an compile error:

Int is not an instance of Show

**Comment by Ingo60** [comment]
I get

    ()->IO Int is not an instance of Show

and this is correct, since we have here a function

    () -> IO Int

that is  you need to write:

     proc <- System.availableProcessors ()
    putStrLn("processor count " ++ show proc)

Your native definition is quite practical, yet it would, for example, allow the compiler to create a constant instead of actually calling `java.lang.Runtime.getRuntime().availableProcessors()` each time you mention it.

I'm not sure about the OS/JVM implementations, but couldn't it be the case that the processor count actually changes during runtime (for example, when the code runs in a VM). In such a case, it could be interesting to get the number of available processors **at a certain point in time** which could vary over time.

**Comment by russel** [comment]
Aha, I am getting error message with line breaks and got slightly misled:

 ()→IO
    Int is not an instance of Show

is the actual message I get. Thanks for spotting the semantics behind the syntax.

Should:

show (System.availableProcessors ())

work?

**Comment by Dierk** [comment]
you can do

System.availableProcessors() >>= println

if you want to have show explicitly in the mix you have to put the pure show function into the IO context by using return

System.availableProcessors() >>= return . show

cheers
Dierk

**Comment by russel** [comment]
Thanks Dierk, I had (obviously) missed (despite it being obvious) that System.availableProcessors is "monadic".

**Comment by russel** [comment]
I can't decide whether I prefer the native call approach or the:

processorCount <- System.availableProcessors ()
putStrLn("processor count " ++ show processorCount)

approach. Maybe I'll go with this as it requires less hassle with Java Platform.

**Comment by mgajda** [comment]
Would be nice to have standard library proposal for this one...
