### ISSUE TITLE
Add java.lang.Runtime to frege.java.Lang

### ISSUE THREAD

**Issue by seancorfield** [Frege/frege#239]
Where appropriate, expose parts of the Runtime class to Frege to make interop easier.

**Comment by seancorfield** [comment]
Most of the Runtime class is impure but some parts are "pure for the duration of the program" (availableProcessors, maxMemory, totalMemory).

What parts are worth adding? I see `exec` is actually exposed indirectly in frege.lang.Processes -- that seems... odd... since `exec` is not a member of that (Java) class.

**Comment by Ingo60** [comment]
I don't have any issues with that, its just that I was convinced that this class is utterly useless, except for the exec stuff, that we have in Java.lang.Processes, where it properly belongs.

So if it is just for "exec", don't do anything.

**Comment by seancorfield** [comment]
Perhaps expose the processor / memory accessors via frege.java.Lang's `System` then? Given that `exec` is already bundled with `Process`.

Looks like `maxMemory` could be `pure` since the docs give no indication that can change, whereas the other processor / memory functions "may vary over time" so those need to be `IO` types, yes?

**Comment by Ingo60** [comment]
Once we have the type, we can as well do everything except something that would need yet another type that we don't have yet, this is also the reason why I cut out the Process things, as they are seldom needed, but Java.Lang is imported in the Prelude, so on every compile.

But fro consistency I would regard those memory things all as IO. We can also not guarantee hat some fancy JVM implementation doesn't allows memory expansion sometime.

For the duplicate stuff, we just do something like

     foo = System.foo

as this just creates an alias, and no runtime code.

**Comment by seancorfield** [comment]
Note: I did not add tests because other than testing you need numbers back, there's not much you can claim about these new function.
