### ISSUE TITLE
[1,2] !! 0   --> can't resolve `!!`, did you mean `!~` perhaps?

### ISSUE THREAD

**Issue by jorander** [Frege/frege#242]
Hi
As I'm new to both Frege and Haskell I'm following the tutorial (http://learnyouahaskell.com/starting-out) and the Frege adaptions (https://github.com/Frege/frege/wiki/LYAH-adaptions-for-Frege) using Frege REPL.
In the section "Intro to lists" I find the function `!!` to be used to get an element out of a list by index (starting from 0). I see no comment on this in the Frege adaptions.
I try with 
```haskell
[1,2] !! 0 
```
(and many others).
Both in the Frege REPL and when compiling using the Frege command-line tool i get a compile error: "can't resolve `!!`, did you mean `!~` perhaps?"

**Comment by jorander** [comment]
Sorry, I forgot the versions I use.

REPL: frege-repl-1.4-SNAPSHOT
Command-line: frege3.23.422-ga05a487.jar

Same behaviour in both.

**Comment by Ingo60** [comment]
Yes, this is right.
I though this function was only provided by Data.List, so we have it only there.
But it must be in the Prelude, according to the standard.

We'll leave this Issue open, until it is fixed.

Meanwhile, enter the following before you do examples with (!!):

    import Data.List(!!)

**Comment by jooyunghan** [comment]
I found that there is another compatibility issue about importing.

    import Data.List (!!)

should be like this;

    import Data.List ((!!))

**Comment by Ingo60** [comment]
Thanks for noticing. I find this more noisy than necessary, but it'll certainly be possible to support it.

**Comment by Ingo60** [comment]
moved (!!) back to PreludeList
