### ISSUE TITLE
Frege prints runtime after application exit

### ISSUE THREAD

**Issue by sstewartgallus** [Frege/frege#246]
This seems like a wart that's only useful for the compiler. Also, if somebody wants a reproducible build log than that isn't too good.

**Comment by Ingo60** [comment]
This is well discussed, and will be gone with the next release.

**Comment by Ingo60** [comment]
Not anymore.

A reproducible build log is not generally achievable, because the compiler compiles several modules  concurrently. Hence, the order of completion of concurrently compiling modules is non-deterministic.
