### ISSUE TITLE
How do I package up and distribute a final binary for Frege?

### ISSUE THREAD

**Issue by sstewartgallus** [Frege/frege#248]
I could just ship a final built jar along with the compiler jar but I'd prefer not to carry along that much bloat. Mostly I know I don't need the Frege source files embedded in the build and the compiler class files. I know that there are automated tools such as ProGuard that can strip out all the unused classes but I do not know if Frege uses reflection or not which would break such tools assumptions.

**Comment by Ingo60** [comment]
The Frege runtime system and libraries do not use reflection for their own purposes.

However, you can of course do reflection from user code. The compiler, documentation tool and quick check tool actually do this, by reading the annotations that contain meta-information about classes generated with Frege.

So, it is the same situation as with plain Java code: when you're sure your code doesn't need reflection, you can use ProGuard. Actually, I recommend this strongly, see also the sample ProGuard script in the FAQ.
Unfortunately, ProGuard (or some other methods for stripping) is not well supported by build tools.

It goes without saying that when you strip the annotations, you cannot use your artifacts with the aforementioned tools anymore. But this should not be an issue with runnable JARS.
