### ISSUE TITLE
runCompiler in frege.compiler.Main just returns boolean

### ISSUE THREAD

**Issue by rahulsom** [Frege/frege#249]
This is not very helpful when trying to build tools. It would be helpful if it returned a `Pair<Boolean,List<Message>>`

That way the boolean would be interpreted as before, and the list of messages could be warnings and errors from the compiler.

**Comment by Ingo60** [comment]
It depends on your use case. As documented, it is just a convenience method.

It is not the purpose of that module to provide functions for all thinkable circumstances. Rather, the functions there are clients of the compiler infrastructure itself. 

Other programs are using this same infrastructure for different purposes.

See for example `frege.tools.Splitter` , which runs several compiler passes and then prints a graph of function dependencies. Or the eclipse plugin, which runs certain passes up to type-checking when you edit a file, and uses the collected information to provide semantic coloring, error markers, documentation, layout overview, etc. Last, but not least, the REPL is a program to compile code line by line and then run it.
