### ISSUE TITLE
Enhance String.indexOf :: String -> String -> Int

### ISSUE THREAD

**Issue by jwausle** [Frege/frege#250]
Enhance frege.prelude.Prelude.fr

Update type String

-     pure  native indexOf :: String -> Char -> Int 
+    pure  native indexOf :: String -> Char -> Int
+                                       | String -> String -> Int

**Comment by Ingo60** [comment]
What about all the other missing functions?
I'm just saying .... we could as well do them all at once.

**Comment by jwausle** [comment]
I agree. ... I will enhance the String Type and send Second request. 

My first goal was: keep it simple;)

**Comment by Ingo60** [comment]
Pull request merged.
