### ISSUE TITLE
Frege has a problem with JDK9

### ISSUE THREAD

**Issue by russel** [Frege/frege#252]
Now that Gradle runs on JDK9, I discover that Frege has a problem with the changed numbering system as well – the 1. in JDK numbering is finally dropped, JDK9 is JDK9 not JDK1.9. Somewhere there is some version number checking in the Frege code:

|> gradle test
:compileJava UP-TO-DATE
:compileFrege
Exception in thread "main" java.lang.ExceptionInInitializerError
	at frege.compiler.Main.$main(Main.java:7140)
	at frege.compiler.Main$Ĳ$$mainƒd0fa0028.eval(Main.java:7990)
	at frege.compiler.Main$Ĳ$$mainƒd0fa0028.eval(Main.java:7987)
	at frege.runtime.Fun1$1.eval(Fun1.java:63)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.compiler.Main.main(Main.java:8197)
Caused by: frege.runtime.Undefined: strange java.specification.version: Just "9"
	at frege.prelude.PreludeBase.error(PreludeBase.java:18011)
	at frege.compiler.types.Targets$1$1.eval(Targets.java:831)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:257)
	at frege.prelude.Maybe.fromMaybe(Maybe.java:1245)
	at frege.compiler.types.Targets$1.eval(Targets.java:828)
	at frege.compiler.types.Targets$1.eval(Targets.java:821)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at frege.compiler.common.CompilerOptions.<clinit>(CompilerOptions.java:344)
	... 7 more
:compileFrege FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileFrege'.
> Process 'command '/home/users/russel/lib.Linux.x86_64/jdk-9_ea-b96/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.296 secs

**Comment by Ingo60** [comment]
Too bad, must be fixed.

There is just nothing one can rely on. Since Java 5 the numbering is 1.5, 1.6, 1.7, 1.8.

I hope you can do with JDK 1.8 in the meantime.

**Comment by russel** [comment]
It was 1.9 until a couple of betas ago and they made the switch to 9. Obviously the label change should have happened with JDK5, but…

I'll survive with JDK8 (aka JDK1.8) for now. :-)

**Comment by Ingo60** [comment]
Fixed with 087b8fac9019e9bbd62ee3bfe7512bd1dc7d2e69

Will be effective in 3.24 releases.

**Comment by russel** [comment]
Sponditious. Is there an easy way for "end users" to test out stuff based on a Gradle build?

**Comment by Ingo60** [comment]
What you could do is to checkout the "gen8" branch, run

    make runtime fregec.jar

and fiddle around with your gradle build files, so that gradle will use the produced fregec.jar instead of some downloaded one.

**Comment by russel** [comment]
I can easily do that.

This is the real bleeding edge, I like it. :-)

**Comment by Ingo60** [comment]
I regularly do this gradle hacking when I build the repl to get the bleeding edge version used.

**Comment by russel** [comment]
Is byacc or byaccj the better dependency to have installed?

**Comment by Ingo60** [comment]
I used byaccj under Windows and currently use byacc in Linux. I think it doesn't matter, both should do.

**Comment by Ingo60** [comment]
Just noticed that the latest released compiler was not able to compile the new code.
I've uploaded a frege3.23.24a.jar that can.

**Comment by russel** [comment]
535 anglides:/home/Checkouts/Git/Git/Frege (git:gen8)
|> make runtime fregec.jar
mkdir -p build
javac -encoding UTF-8 -d build -nowarn -source 1.7 -target 1.7 frege/runtime/*.java frege/run/*.java frege/run7/*.java
javac -encoding UTF-8 -d build frege/run8/*.java
Runtime is complete.
java "-Dfrege.javac=internal" -Xss4m -Xmx3g -cp build  -jar fregec.jar  -d build -hints -prefix a -sp shadow:.  -make frege.compiler.Main
Error: Unable to access jarfile fregec.jar
Makefile:261: recipe for target 'compiler1' failed
make: *** [compiler1] Error 1

**Comment by Ingo60** [comment]
The Makefile expects that the compiler you want to use is in the working directory under the name `fregec.jar`
Please download the frege3.23.24a.jar I mentioned before from https://github.com/Frege/frege/releases/download/3.23.288/frege3.23.24a.jar

**Comment by russel** [comment]
OK, done,  now compiling. Would it be better to have the boostrap in the repository? Or is this just a temporary glitch?

**Comment by russel** [comment]
It seems that the fregec.jar resulting from compiling the gen8 branch HEAD runs fine on JDK9.

**Comment by Ingo60** [comment]
It would probably be ok to have the java files that are needed to make a running frege compiler in the repository. This would make it possible to git pull and make everything from sources. Though, if you ask me, the java files produced by the frege compiler are not really readable.

**Comment by Ingo60** [comment]
The problem has been solved.
