### ISSUE TITLE
Native data declaractions cannot contain 'data' in package path.

### ISSUE THREAD

**Issue by LGLO** [Frege/frege#253]
```
data FJEqual a = native fj.Equal
data FJEither a b = native fj.data.Either
```
The first is OK, while for second line error is reported:
`syntax error, a valid java identifier cannot start
    with token "data"`

This looks like some parser bug.

**Comment by Ingo60** [comment]
Lech,

just for this scenario, there is the alternative to enclose the native item (be it class names or method names, qualified or not) in double quotes:

    data FJEither a b = native "fj.data.Either"

should work.

**Comment by LGLO** [comment]
Works. Thank you!
