### ISSUE TITLE
JSONExample.fr won’t compile: 'optional' can’t be resolved

### ISSUE THREAD

**Issue by 0dB** [Frege/frege#256]
Trying to load `frege/examples/JSONExample.fr`, I get ```can't resolve `optional````.

In REPL, executing ```import Data.JSON``` does not list `optional` either, though it is in there.

Using Frege REPL 1.4 SNAPSHOT.

**Comment by Ingo60** [comment]
The change history and the release notes tell me that `optional` first appears in Data.JSON in the 3.23.401 release. What does your REPL tell you if you say

    :version

**Comment by 0dB** [comment]
Updated, works, thanks. (And tripped over the “Fail” right away, ha ha!). Good stuff in JSON.fr—and thanks for all the documentation—, now going to have some fun—and actually get some current work done with it.
