### ISSUE TITLE
Explicitly forbidden fantom parameters for type synonyms.

### ISSUE THREAD

**Issue by Heimdell** [Frege/frege#257]
Disclaimer: I understand that Haskell and Frege are different languages.

What is the reason behind this? Fantom parameters are very good haskell pattern.

GHCi is happy with
```haskell
type Lens s t a b = forall f . Functor f => (a -> f b) -> (s -> f s)
```
declaration, but [http://try.frege-lang.org/](url) says:
```
N: E <console>.fr:N: bound type variable(s) t not appearing in type
```

**Comment by Ingo60** [comment]
This is clearly not as it should be.
