### ISSUE TITLE
Ord shouldn't be a superclass of Num

### ISSUE THREAD

**Issue by lambda-11235** [Frege/frege#259]
Ord seems to be a superclass of Num. However, not all numbers are orderable. This may present problems for complex number, quaternion, matrix, and vector data type implementations.

**Comment by Ingo60** [comment]
This topic will be addressed in the course of establishing Haskell 2010 compatibility, see also #226 

It would be most welcome to fill in some details in issue #226, taking into account that dictionary passing is costly and the primitive number types **are** orderable. Thus, a solution where simple programs like

    foo a = if a > 0 then a+a else 1+negate a

wouldn't need 2 constraints would be great.
