### ISSUE TITLE
emitting javascript

### ISSUE THREAD

**Issue by sonwh98** [Frege/frege#262]
Can the frege compiler be retrofitted to emit javascript instead of JVM bytecode?
I'm doing a lot of Clojure/ClojureScript. It is great because I can use one uniform language for both frontend and backend.  It would be great if Frege can do the same because having a haskell like type system can be a life saver. I know GHCJS and elm exist but I'd like to stick to the JVM ecosystem

**Comment by Zenleaf** [comment]
Hi I had the same thought, not sure if it can be retrofitted. I'm currently using Purescript for frontend. Having a Fregescript would be superb though.

**Comment by Dierk** [comment]
Since Frege compiles to Java source code, you can use any Java to JavaScript converter like GWT or Vaadin for that purpose.

**Comment by Ingo60** [comment]
Being absolutly illiterate with regard to JS, I cannot really answer this.

But, given that PureScript and GHCJS exist, it should be absolutly possible to do "the same".
I cannot judge how good GHCJS is from the point of view of a JS user, but it seems to be proof that
general concepts of pure FPLs can somehow be mapped to JS. 

Assuming this, it would be a matter of:

  - providing a compiler backend
  - looking for a way to handle the module/separate compilation story (i.e. how would `import` work?)
  - developing a Prelude that doesn't rely on native JAVA functions.

**Comment by Zenleaf** [comment]
Coming from Clojure I can see their motivation for a Clojure that compiles to JavaScript as there were no lisp that compiles to JavaScript. However regarding Frege we already have GHCJS, Haste, Purescript, Elm.

But if we do have Frege compile to JavaScript as well then we could also do what Clojure does using reader conditionals (.cljc) allowing us to have libraries with 1 codebase that can be used by Frege and "Fregescript"

**Comment by Ingo60** [comment]
Question was answered, I think.
