### ISSUE TITLE
Unfortunate name

### ISSUE THREAD

**Issue by yann-joachim** [Frege/frege#267]
The name Frege could be perceived as offensive by some people : [Gottlob Frege](https://en.wikipedia.org/wiki/Gottlob_Frege#1924_diary)

**Comment by Ingo60** [comment]
Do you have a proposition or suggestion, or can we close this issue?

**Comment by yann-joachim** [comment]
Well I just find the choice of this name disturbing, there are many great
logicians with less radical political views.

Le dim. 6 mars 2016 à 23:10, Ingo Wechsung <notifications@github.com> a
écrit :

**Comment by Ingo60** [comment]
> political views

This is exactly why I think this is entirely off-topic here on github. 
For discussing politics, etc., please use the appropriate social networks.
