### ISSUE TITLE
Feature Request: Java 8 build

### ISSUE THREAD

**Issue by jprante** [Frege/frege#275]
I'm new to Frege. When I want to build with my (forked) gradle-plugin-frege and Java 8, all I get are errors:

Plugin build.gradle

```
dependencies {
  compile gradleApi()
  compile localGroovy()
  compile 'org.frege-lang:frege:3.24-7.30'
  compile 'org.frege-lang:frege-repl-core:1.3'
  compile 'org.frege-lang:frege-native-gen:1.3'
  compile 'org.functionaljava:functionaljava:4.5'
}
```

Project build.gradle

```
dependencies {
    compile 'org.frege-lang:frege:3.24-7.30'
}

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

```

HelloFrege.fr

```
--- Documentation for HelloFrege
module HelloFrege where

--- Documentation for greeting
greeting = "Hello Frege"

main _ = do
    println greeting
```

```
gradle build
E /Users/joerg/Projects/github/xbib/frbr/src/main/frege/HelloFrege.fr:1: cannot import frege.Prelude
    compiled for target  1.7 (without lambda support)
    when the current target  1.8 has lambda support
    Try to use compiler option -target 1.7
```

I do not want to use `-target 1.7` because Java 7 is outdated.
Please publish artifacts for frege 3.24+ with Java 8 compatibility.

**Comment by Ingo60** [comment]
If you want the java8 build, why then do you write:

    compile 'org.frege-lang:frege:3.24-7.30'

The `-7` specifically adresses the Java7 compatible build.

**Comment by jprante** [comment]
The only release of Frege 3.24 I can find is 3.24-7.30 http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.frege-lang%22%20AND%20a%3A%22frege%22

So I have to build a Frege 3.24 for Java 8 from source by myself?

**Comment by Ingo60** [comment]
Not at all, as they are published on the [releases page](https://github.com/Frege/frege/releases).

I really think your request belongs [here](https://github.com/Frege/frege-gradle-plugin)
