### ISSUE TITLE
Two forall a in a type signature get confused

### ISSUE THREAD

**Issue by mabre** [Frege/frege#277]
Quoting @Ingo60 from the mailing list

> It happens in function `everywhere`, which has the perfect (though not quite intuitive) type siganture:
> 
> ``` haskell
> (forall a. Data a => a -> a) ->  (forall a. Data a => a -> a)
> ```
> 
> In the java-generation phase, the two different "a"-types get confused, which leads to the crash.
> 
> (But this is merely an inconvenience, what is worse is that another error arises when we rename the  a's in the result to b's.
> It must somehow have to do with gfoldT but it shouldn't clearly not happen that type variables of different functions influence each other)
> 
> However, once we don't replace with b, but with c, the frege compiler succeeds.

The code which fails to compile (probably no minimal test case):

``` haskell
module EverywhereCrash where

import Data.Maybe

main = print $ invert [-1,0,1]

invert :: [Int] -> [Int]
invert = everywhere (mkT inv)
      where
          inv :: Int -> Int
          inv i = -i

-- from the original Data class in ghc and
-- https://github.com/rdegnan/typeable
everywhere :: (forall a. Data a => a -> a)
           -> (forall a. Data a => a -> a)
everywhere f = f . gmapT (everywhere f)

mkT :: ( Typeable a
       , Typeable b
       )
    => (b -> b)
    -> a
    -> a
mkT = extT id

extT :: ( Typeable a
        , Typeable b
        )
     => (a -> a)
     -> (b -> b)
     -> a
     -> a
extT def ext = (T.unT) ((T def) `ext0` (T ext))

ext0 :: (Typeable a, Typeable b) => c a -> c b -> c a
ext0 def ext = maybe def id (gcast ext)

gcast :: (Typeable a, Typeable b) => c a -> Maybe (c b)
gcast x = r
 where
  unsafeCoerce = unsafeCoerce_
  r = if typeOf (getArg x) == typeOf (getArg (fromJust r))
        then Just $ unsafeCoerce x
        else Nothing
  getArg :: c x -> x
  getArg = undefined

pure native unsafeCoerce_ java.util.Objects.requireNonNull {a} :: a -> b

data T x = T { unT :: x -> x }
data ID x = ID { unID :: x }

instance Data a => Data [a] where
  gmapT  f   x = case x of
                      [] -> []
                      (y:ys) -> (f y:f ys)

instance Data Int

class Typeable a => Data a where
  gfoldl :: (forall d b. Data d => c (d -> b) -> d -> c b)
         -> (forall g. g -> c g)
         -> a
         -> c a
  gfoldl _ z = z
  gmapT :: (forall b. Data b => b -> b) -> a -> a
  gmapT f x0 = (ID.unID) (gfoldl (\(ID c) x -> ID (c (f x))) ID x0)

instance Typeable a => Typeable ([] a) where
  typeOf _ = "prelude.List.Int"
instance Typeable Int where
  typeOf _ = "prelude.Int"

class Typeable a where
  typeOf :: a -> String
```

Exception at runtime with frege 3.23.451:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.ClassCastException:
EverywhereCrash$IData_$lbrack$rbrack cannot be cast to frege.runtime.Lambda
        at EverywhereCrash.everywhere(EverywhereCrash.java:985)
```

Exception at compile time with frege 3.24.61:

```
frege.runtime.Undefined: Can't adapt
Bind {a → a, Func.U<𝓐, 𝓐>, RunTM.<Func.U<CData<𝓐>, Func.U<𝓐,
𝓐>>>cast(arg$1).apply(Thunk.<CData<𝓐>>lazy(ctx$1)).call()}
to  Func.U<CData<Object>, Func.U<Object, Object>>
because  𝓐  does not match  CData<Object>
```

**Comment by yuxuanchiadm** [comment]
Minimal test case attached:
```
class Bar a

foo :: (forall a. Bar a => a -> a) -> (forall a. a -> a)
foo f = foo f
```

**Comment by Ingo60** [comment]
@yuxuanchiadm 

I don't see how this is a good test case. Please note that the type signature you have given is equivalent to:

    foo :: forall b. (forall a. Bar a => a -> a) -> b -> b

And now, it must typecheck, since under the premise that `foo x` gives `b -> b`, clearly `foo x` will give `b -> b`

A similar example would be:

    bar :: Int -> String
    bar n = bar n

**Comment by Ingo60** [comment]
I think this was saved for a long time together with #278 
At least, `tests/comp/Issue277.fr` (which is a copy of the code above) compiles and runs just fine.

**Comment by yuxuanchiadm** [comment]
Sorry about the lack of description. The problem is that compiler just simply crashed when compile:
```
class Bar a

foo :: (forall a. Bar a => a -> a) -> (forall a. a -> a)
foo f = foo f
```
Notice this will works fine:
```
class Bar a

foo :: (forall a. Bar a => a -> a) -> (forall b. b -> b)
foo f = foo f
```

**Comment by yuxuanchiadm** [comment]
Also there is a reason to write test case as ```foo f = foo f``` instead of ```foo = foo```.
Compiled fine without any crash:
```
foo :: (forall a. Bar a => a -> a) -> (forall a. a -> a)
foo = foo

foo :: (forall a. Bar a => a -> a) -> (forall b. b -> b)
foo = foo

foo :: (forall a. Bar a => a -> a) -> (forall b. b -> b)
foo f x = foo f x
```
Crashed compiler:
```
foo :: (forall a. Bar a => a -> a) -> (forall a. a -> a)
foo f x = foo f x
```

**Comment by Ingo60** [comment]
You are right.

It is instructive to compare the output of the compiler with trace flags -xg and -xz, once for each type signature.

Questions to solve:

  1. I thought I had put some code in that renames the type variables in such a way that no to foralls in the same type signature share any type variable name. Why doesn't it work?

  2. If one compiles the version that works, the compiler (correctly) decides to pass on `f` as is, while in the wrong version it tries to find the constraint `Bar a` (and this fails, of course, since `foo` doesn't have a constraint). The only difference is AFAICS the name of the type variable. How's that possible?
