### ISSUE TITLE
Sigma problems

### ISSUE THREAD

**Issue by Ingo60** [Frege/frege#278]
There are a number of severe problems with user supplied forall types:

    (forall a. a -> a) -> a -> a

gives an error message.

The following does compile up to code generation, where it crashes (See also #277 )

    type GenericQ x = (forall b. Data b => b -> x)
     everything :: (a2 -> a2 -> a2) -> GenericQ a2 -> GenericQ a2

This is especially alarming since the expansion:

    everything :: forall b.Data b => (a2->a2->a2) -> (forall b.Data b => b -> a2) -> b -> a2 

is not a valid type at all, so it shouldn't even compile.

**Comment by Dierk** [comment]
I wonder if that is that same problem that I get with https://github.com/Dierk/HelloFrege/blob/sample_code/src/main/frege/BasicLens.fr#L64

It all compiles fine and works well until line 64 where it fails at runtime with
```
Exception in thread "main" java.lang.ClassCastException: frege.runtime.Fun1$1 cannot be cast to frege.prelude.PreludeMonad$CFunctor
	at BasicLens$6$1$1.eval(BasicLens.java:2603)
	at BasicLens$6$1$1.eval(BasicLens.java:1)
	at frege.runtime.Fun1$1.eval(Fun1.java:63)
	at frege.runtime.Delayed.call(Delayed.java:198)
	at frege.runtime.Delayed.forced(Delayed.java:267)
	at BasicLens$6$1.eval(BasicLens.java:2627)
```

**Comment by Ingo60** [comment]
Not sure, but my gut tells me it is at least related.

You could help me to solve this problem by reducing it to a minimal example.

**Comment by Dierk** [comment]
as minimal as I can get is below. You can paste it in the online repl, import, call main [] and see the error.
View on a simple lens works just fine. Only at composition, the runtime error occurs.

```
module BasicLens where

import frege.data.wrapper.Const 

getConst :: Const a b -> a
getConst (Const a) = a

type Lens s a = forall f. Functor f => (a -> f a) -> s -> f s

view :: Lens s a -> (s -> a)
view lens = getConst . lens Const

data Portfolio  = Portfolio { position  :: Position   }
data Position   = Position  { soMany :: Int }

soManyLens :: Lens Position Int 
soManyLens f p = fmap  p.{soMany =} (f p.soMany)

positionLens :: Lens Portfolio Position
positionLens f p = fmap p.{position =} (f p.position)

main _ = do        
    println $ view (positionLens . soManyLens) Portfolio{position= Position 0}
```

**Comment by Ingo60** [comment]
Great, thanks. 
Meanwhile, you can try the following workaround. 

Manually expand the type aliases that feature a forall, but make sure to use a different name for the bound variable each time.

**Comment by Dierk** [comment]
I wasn't successful with the type expanding. This is lack of knowledge on my side, I guess, since I didn't know how to define the then unbounded a and s.

However, this specialized version works (not sure if that helps):

```
view :: Lens (Const a b) a -> (Const a b) -> a
view lens = getConst . lens Const
```

**Comment by Ingo60** [comment]
> This is lack of knowledge on my side, I guess, since I didn't know how to define the then unbounded a and s.

This, I think, is exactly what is true for the compiler as well, and what causes it to malfunction.

**Comment by Dierk** [comment]
so I'm at least in good company ;-)

**Comment by Dierk** [comment]
cool, thanks! Can't wait to put that in my code :-)
