### ISSUE TITLE
http://try.frege-lang.org/ is down

### ISSUE THREAD

**Issue by ndmitchell** [Frege/frege#280]
Since yesterday. It gives me a 502 proxy error.

Ping @mmhelloworld, since this takes out the Hoogle Frege instance, and in fact the whole Hoogle update process.

**Comment by mmhelloworld** [comment]
Hi Neil,

Sorry about that. For some reason, the AWS server that the online REPL is running on went down. I have now restarted the server and it is up now.

**Comment by ndmitchell** [comment]
Thanks, all working fine now. Can I recommend you use https://uptimerobot.com/ to check the site is alive? That was what first reported to me that Hoogle wasn't upgrading.

**Comment by mmhelloworld** [comment]
I have now setup a monitor for Frege REPL. Thank you for the information about UptimeRobot!

**Comment by ndmitchell** [comment]
The site seems down again - this time with a 500.

**Comment by mmhelloworld** [comment]
@Dierk I am trying to login to the server using ssh but I am getting `No route to host` error. Any idea about the status of the server?

**Comment by Dierk** [comment]
Up again. 

Dierk

sent from:mobile

**Comment by ndmitchell** [comment]
Down again @Dierk @mmhelloworld 

Can I recommend https://uptimerobot.com/? It's how I first knew your site was done.

**Comment by mmhelloworld** [comment]
@ndmitchell It is up now. I have also added @Dierk as an alert contact for uptimerobot.com so hopefully this should get resolved soon in the future.

**Comment by ndmitchell** [comment]
Thanks @mmhelloworld

**Comment by Dierk** [comment]
looks like I get no more notifications from uptimerobot. @ndmitchell, any idea why that might be?

**Comment by mmhelloworld** [comment]
Hi @Dierk ,

I just checked uptimerobot settings. You are I are still part of notification contacts. I got a notification on May 18th when the REPL went down. I am not sure why you (your Canoo email) haven't got that.

**Comment by Dierk** [comment]
Oh, that is an outdated address. Could you please change that to codevise at me dot com?

**Comment by ndmitchell** [comment]
I confirm I got the alert pretty much immediately (but was busy all weekend!)

**Comment by Dierk** [comment]
up again

**Comment by ndmitchell** [comment]
Down again!

**Comment by Dierk** [comment]
thx for the note. up again.

**Comment by ndmitchell** [comment]
`try.frege-lang.org` seems 100% disappeared and `frege-lang.org` directs off to the GitHub page.

**Comment by Dierk** [comment]
yes, thx for the note. The repl is temporarily disabled until we moved to a new server after vacation. Sorry for the inconvenience.

**Comment by ndmitchell** [comment]
No worries, I've disabled generation of Frege stuff, so ping me once it's all back and I'll put it back in.
