### ISSUE TITLE
+ binds tighter than .&.

### ISSUE THREAD

**Issue by mabre** [Frege/frege#281]
The program

``` haskell
module Prio where
import Data.Bits
main = putStrLn $ show ( (8::Int) + (2::Int) .&. (3::Int))
```

prints `10` in Haskell, but `2` in Frege, because the `+` binds tighter than `.&.` in Frege. In Frege, `+` has precedence 13 and `.&.` 11, whereas in Haskell `+` has 6 and `.&.` has 7.

**Comment by Ingo60** [comment]
Yes, this is so.  Frege goes here with the operator precedences used in C, Java, Perl, etc.

I'm afraid it would break some code when we changed this right now. Hence, I'd rather leave it as is, even if I see the problem. Luckily, operator fixities aren't carved in stone, so there will be workarounds.
