### ISSUE TITLE
Pattern matching on negative number is not allowed

### ISSUE THREAD

**Issue by mabre** [Frege/frege#282]
The following code works fine in GHC, but Frege says ``application of  negate  is not allowed in patterns.``
```haskell
main = case i of
            (-1) -> putStrLn "-1"
            _    -> putStrLn "_"
    where i = -1
```
A workaround is using ``if`` instead of ``case``.

**Comment by Ingo60** [comment]
Duplicate of #26 

Another workaround would be

    main = case i of
        neg | neg == -1 = pitrStrLn "negative"

I'm closing this because of duplication.
