### ISSUE TITLE
ForkIO - ThreadPoolExecutor

### ISSUE THREAD

**Issue by corporatepiyush** [Frege/frege#283]
It would be make more sense to make use of ThreadPoolExecutor of max size which is twice the number of available processor and min size of 1 or ZERO instead of ExecutorService.newFixedThreadPool.

FixedThreadPool, once initialized, makes use of static number of threads which may be resource intensive as it may happen that it may not be used very frequently.

**Comment by Ingo60** [comment]
The Pool is only created when `forkIO` is actually executed, so the overhead is zero for non-asynchronous programs.

When you have just a small number of dedicated parallel tasks, you could use `forkOS`, which creates just a single thread, without further overhead.

Do you have an example where use of `forkIO` actually and noticeably degrades performance?

**Comment by corporatepiyush** [comment]
JVM maps threads 1:1 with native threads.  when Threads are not usable (or idle) it still adds overheads to system resources.
Creating ThreadPoolExecutor with optimum min and max size will create threads as needed, whereas creating ThreadPoolExecutor with `ExecutorService.newFixedThreadPool` leads to min and max thread values to be same.
