### ISSUE TITLE
frege compiler should emit error message for implementation restriction

### ISSUE THREAD

**Issue by taojang** [Frege/frege#286]
I'm using frege 3.24-7.100 and when I uncomment the Functor instance I defined here
https://github.com/taojang/frege-flink/blob/dd1c7252c29ce7730625452d9ce4a2c2165371e0/src/main/frege/java/flink/DataStream.fr#L14

and recompile the project with `gradle build`

I get the following error:

```
/path-to-project/build/classes/main/frege/java/flink/DataStream.java:133: error: cannot find symbol
  implements PreludeMonad.CFunctor<org.apache.flink.streaming.api.datastream.DataStream<𝓐>>
                                                                                        ^
  symbol:   class 𝓐
  location: class DataStream
/path-to-project/build/classes/main/frege/java/flink/DataStream.java:142: error: incompatible types: frege.run.Kind.U<DataStream<?>,𝓐> cannot be converted to DataStream<𝓐>
        >fmap(arg$1.call(), arg$2.call());
                                      ^
  where 𝓐,𝓑 are type-variables:
    𝓐 extends Object declared in method <𝓐,𝓑>ƒfmap(Lazy<frege.run7.Func.U<𝓐,𝓑>>,Lazy<frege.run.Kind.U<DataStream<?>,𝓐>>)
    𝓑 extends Object declared in method <𝓐,𝓑>ƒfmap(Lazy<frege.run7.Func.U<𝓐,𝓑>>,Lazy<frege.run.Kind.U<DataStream<?>,𝓐>>)
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
2 errors
E /path-to-project/src/main/frege/java/flink/DataStream.fr:15: java
    compiler errors are most likely caused by erroneous native
    definitions
Java.flink.DataStream: build failed because of compilation errors.
Java.flink.Env: build failed because module `Java.flink.DataStream` not built.
Simple: build failed because module `Java.flink.Env` not built.
Build failed.

```

**Comment by taojang** [comment]
I have no better idea to describe this issue though... Please change the title when you see fit :)

**Comment by Ingo60** [comment]
No problem. 
One question : is DataStream indeed generic?

**Comment by taojang** [comment]
Yes it is. The source code is here:
https://github.com/apache/flink/blob/c4bbed9e4d43950244150c5ffcfd4a47f6f1c64e/flink-streaming-java/src/main/java/org/apache/flink/streaming/api/datastream/DataStream.java

Thank you for the quick response!

**Comment by Ingo60** [comment]
Well, this is an implementation restriction in the current implementation.
(Arguably, the frege compiler should detect it and issue an error message.)

The restriction is that no native type constructor can be used where a higher kinded type is required.
Or, to put it differently, type constructors for native types are not higher kinded.

The Functor, Monad and Applicative type classes all demand a type of kind

    * -> *

so we can make `Functor []` , `Functor Maybe` or `Functor (Either a)`

To implement something approximating a native functor, you'd need to wrap your native type in an ordinary  `data`

    data Native' a = native x.y.z.N where
        nmap :: (a -> b) -> Native' a -> Native' b
    data Native a = N (Native' a)
    instance Functor Native where
        fmap f (N n) = Native'.nmap f n

I shall implement the error message, thus this issue remains open,

**Comment by Ingo60** [comment]
When we implement this, we'll have the problem that we couldn't make instances for higher kinded type classes even if the java type actually implements `frege.run.Kind` interfaces.

We could check that out, however.

**Comment by Ingo60** [comment]
There is now an extra check for native types to see if the appropriate kind interface is implemented.
