### ISSUE TITLE
Document the run command line in the getting started guide

### ISSUE THREAD

**Issue by tieTYT** [Frege/frege#289]
In [the getting started guide](https://github.com/Frege/frege/wiki/Getting-Started), the compile command line is documented well and each piece is explained.  But I'd like the run command line to be documented the same way.  Here it is:

```
$ java -Xss1m -cp build:fregec.jar examples.SimpleIO
```

Also, usability suggestion:  I think you should swap the -cp argument so it says `fregec.jar:build`

**Comment by Dierk** [comment]
-cp defines the classpath. 
It consists of two roots: the 
build
subdir and the fregec.jar. 
The colon after build is the path separator (semicolon on windows)

Cheers
Dierk

**Comment by Ingo60** [comment]
That same introduction also says:

> You should already know ... how to run the `java` command in a command line window.
