### ISSUE TITLE
Infer dedent from `where` token after `do` block

### ISSUE THREAD

**Issue by carymrobbins** [Frege/frege#291]
The following is valid Haskell, so it'd be nice for it to be supported by Frege. For now (as a workaround), I'm simply dedenting the `where` token by one character.

```frege
foo :: Monad m => m ()
foo = do
  x <- y
  return x
  where
  y = return ()
```

**Comment by mabre** [comment]
duplicate of #272
The code can be compiled with version 3.24.100.
