### ISSUE TITLE
Wiki about apostrophes

### ISSUE THREAD

**Issue by kstarikov** [Frege/frege#292]
In https://github.com/Frege/frege/wiki/LYAH-adaptions-for-Frege#babys-first-functions-subject-to-review-by-mmhelloworld : 

> In Frege, the apostrophe is only allowed at the end of a name

But in Frege repl (version 3.24.30) it looks as follows:

```frege
frege> conanOBrien' = "It's a-me, Conan O'Brien!"
function conanOBrien' :: String

frege> conanOBrien'
java.lang.NoSuchFieldException: conanOBrien'
```

By the way, having the apostrophe in the middle of the name leads to the same results:

```frege
frege> conanO'Brien = "It's a-me, Conan O'Brien!"
function conanO'Brien :: String

frege> conanO'Brien
java.lang.NoSuchFieldException: conanO'Brien
```

However, if I define it as a function with an argument, it works:

```frege
frege> conanO'Brien a = "It's a-me, Conan O'Brien!" ++ a
function conanO'Brien :: String -> String

frege> conanO'Brien "foo"
It's a-me, Conan O'Brien!foo
```

**Comment by Ingo60** [comment]
This looks like a bug in the REPL, it also appears in the online REPL.

However,

    conanO'Brian = "foo"
    id conanO'Brian 

does work.

Needs more investigation.

**Comment by mmhelloworld** [comment]
I am investigating on the REPL side.

**Comment by mmhelloworld** [comment]
Ok, I am confirming that this is REPL bug. For `conanOBrien'`, compiler is generating a field with name `conanOBrien$tick`. When we just evaluate the field with `frege> conanOBrien'`, REPL is trying to evaluate the field value by looking up the field on the generated class using reflection with name `conanOBrien'` hence the `NoSuchFieldException`.

With `conanO'Brien a` function case and `id conanO'Brian` case, REPL is not directly interpreting `conanO'Brien` but the result of those expressions so these cases succeed.
