### ISSUE TITLE
BigInt Optimisation

### ISSUE THREAD

**Issue by Zylviij** [Frege/frege#295]
These constants are slightly faster than `new java.math.BigInteger("1");`:
    `java.math.BigInteger.TEN`
    `java.math.BigInteger.ONE`
    `java.math.BigInteger.ZERO`

**Comment by Ingo60** [comment]
Yes, I know.
Exactly those constants are employed since inception of this type.

See `Integer.zero` `Integer.one` and `Integer.ten`
