### ISSUE TITLE
Prelude function words sometimes returns empty string as first element

### ISSUE THREAD

**Issue by thomasjohnsson** [Frege/frege#301]
Prelude function 'words' returns an empty string as the first element when the first character(s) in the argument string is/are space character(s).
Examples:
    println (words " A B ") -- > ["", "A", "B"]
    println (words "A B ")  -- > ["A", "B"]
    println (words " ")     -- > []
    println (words "")      -- > []
    println (words " A")    -- > ["", "A"]
    println (words "\tA")   -- > ["", "A"]

-- Thomas

**Comment by Ingo60** [comment]
Here is a GHCi session:

    Prelude> words " one two three"
    ["one","two","three"]
    Prelude> lines "\none\ntwo\nthree"
    ["","one","two","three"]

Here is the same in Frege:

    frege> words " one two three"
    ["","one","two","three"]
    frege> lines "\none\ntwo\nthree"
    ["","one","two","three"]

One can argue what is better, but I feel a strong desire to have `words`  and `lines` consistent.

**Comment by Ingo60** [comment]
See also [my SO question](http://stackoverflow.com/questions/39047943/inconsistent-behavior-of-lines-and-words) concerning this.

**Comment by thomasjohnsson** [comment]
I would wish/hope that compatibility with Haskell2010 whenever possible would be given the highest priority. Otherwise, one might get some hard-to-find bugs when porting code to Frege.
