### ISSUE TITLE
Data definition incompatibility

### ISSUE THREAD

**Issue by praalhans** [Frege/frege#313]
Frege differs from Haskell 2010 with respect to the `data` keyword.

For example the following snippet is valid in Haskell 2010:

```
data Empty
```

but generates a parse error in Frege. Another annoyance when porting Haskell code to Frege is the `deriving` clause.

```
data Example = C1 | C2 deriving (Show, Eq)
```

is valid Haskell 2010 but not parsed correctly by Frege.

See https://www.haskell.org/onlinereport/haskell2010/haskellch4.html#x10-680004.2

**Comment by pasniak** [comment]
Similar here...  Frege's lack of functions for record members makes it daunting, specifically the lines commented out below build in Haskell :

```
---import Prelude
data Coords = Coords { latitude::Double, longitude::Double}
---    deriving (Show)

c = Coords {latitude=10.0, longitude = 1.0} 
--- l = latitude c
```
I was unable to find how to accomplish in Haskell Frege's _primary expressions_ (with dot). Would Lens work?

(Haskell tooling seems robust: Frege has no holes (_), error messages are better, ghcid nicely shows exact error line numbers...)

**Comment by mmhelloworld** [comment]
@pasniak 

> Frege's lack of functions for record members

Frege indeed has functions for record members and also supports `deriving` but in a different syntax as demonstrated below.

```Frege
frege> data Coords = Coords { latitude::Double, longitude::Double}
data type Coords :: *

frege> c = Coords {latitude=10.0, longitude = 1.0} 
function c :: Coords

frege> Coords.latitude c
10.0

frege> c.latitude
10.0

frege> derive Show Coords
instance Show Coords

frege> c.{latitude = 50}
Coords 50.0 1.0

frege> Coords.{latitude = 30} c
Coords 30.0 1.0

frege> c.{latitude = 50, longitude = 2.0}
Coords 50.0 2.0

frege> c.{latitude <- (+20)}
Coords 30.0 1.0
```
There are few more things we could do with Frege's inbuilt record support like nested field updates, checking for fields presence as described [here](http://mmhelloworld.github.io/blog/2014/03/15/frege-record-accessors-and-mutators/).
