### ISSUE TITLE
Unable to find or load main class

### ISSUE THREAD

**Issue by abhi18av** [Frege/frege#316]
Hello Frege team:)

I've gone through the basic setup of `frege` - repl, gui-repl etc but when I wish to setup local aliases for global settings I am having trouble following this [Getting Started](https://github.com/Frege/frege/wiki/Getting-Started)

1. I can only compile for `-target 1.7`
2. `-d build` flag isn't working 

_The above two are really minor issues_

The *major* issue is that even though I have the shell aliases set as 

```bash
alias fregei="$HOME/.frege/bin/frege-repl"
alias fregec="java -Xss1m -jar $HOME/.frege/lib/fregec.jar -target 1.7 "
```

I can't figure out how to run the compiled classes 
```bash
> java -Xss1m -cp build:fregec.jar examples.SimpleIO
Error: Could not find or load main class examples.SimpleIO
```

I've also tried sticking to the directory structure from recommended in the Getting started guide, 
Here's my tree

```bash
❯ tree
.
├── Brainfuck.fr
├── CombinatorEvolution.fr
├── CommandLineClock.fr
├── Concurrent.fr
├── DamenF.fr
├── DigitSum.fr
├── Distance.fr
├── Diverge.fr
├── Euler.fr
├── Euler12.fr
├── Euler7.fr
├── Euler87.fr
├── Euler92.fr
├── Euler93.fr
├── Euler94.fr
├── Euler95.fr
├── EulerLib.fr
├── Evolution.fr
├── FBodies.fr
├── ForH.fr
├── Fpidigits.fr
├── FunctionInstances.fr
├── GoldenRatio.fr
├── Grep.fr
├── HigherOrder.fr
├── JHashMap.java
├── JSONExample.fr
├── KindFunc.fr
├── LBodies.fr
├── MapTest.fr
├── MoreTailCall.fr
├── NumericLiterals.fr
├── PointFree.fr
├── Postfix.fr
├── Records.fr
├── RefExample.fr
├── ReverseStdin.fr
├── SimpleIO.fr
├── Sudoku.fr
├── SwingExamples.fr
├── TailCalls.fr
├── UnicodeChars.fr
├── Welcome.fr
├── YearNumbers.fr
├── euler-sudoku.txt
├── examples
│   ├── SimpleIO$1$1$1.class
│   ├── SimpleIO$1$1.class
│   ├── SimpleIO$1$2$1.class
│   ├── SimpleIO$1$2.class
│   ├── SimpleIO$1.class
│   ├── SimpleIO$1Let$11186$1.class
│   ├── SimpleIO$1Let$11186.class
│   ├── SimpleIO$2$1$1$1.class
│   ├── SimpleIO$2$1$1$2.class
│   ├── SimpleIO$2$1$1.class
│   ├── SimpleIO$2$1.class
│   ├── SimpleIO$2.class
│   ├── SimpleIO$3$1.class
│   ├── SimpleIO$3.class
│   ├── SimpleIO.class
│   └── SimpleIO.java
├── fregec.jar
└── top95.txt

1 directory, 63 files
```

**Comment by Ingo60** [comment]
Since you have not created a `build` directory as outlined in the Getting Started document:

1. The `-d build`  won't work. 
2. By omitting `-d` you use the current directory instead, creating the mess you showed above.
3. To find the main class, you need to include your actual build directory `.` instead of `build` in the class path.

Bottom line: Proceed according to **all** steps of the Getting Started guide. If you don't like the name `build` you can call ìt `blubb` or whatever you want, just be sure to substitute it later in the right place.

**Comment by abhi18av** [comment]
Oh! Sorry, I got it mixed up with `build` in context of compilation ( Python/ Jekyll blog background :P )  - Thanks :+1: 

@Ingo60 Hey, I noticed that Haskell's `Data.Vector` is not there in Frege, I've seen the `wish-list` of libraries to be ported - but I'm curious whether any work is being done on Vector or is it even relevant for Frege - a wapper will do perhaps?
