### ISSUE TITLE
Any plans to support the Arrow syntax?

### ISSUE THREAD

**Issue by rongcuid** [Frege/frege#317]
Currently, it seems that this language feature is not present in frege. As an example, use the `->` Arrow:

```
import Control.Arrow
plus :: Int -> Int
plus = proc a -> do
  b <- (+1) -< a
  c <- (+4) -< b
  returnA -< c
```

This is just `(+4) <<< (+1)`. Of course, there are more complicated arrows with features like if/else, etc. Will this syntax be supported?

**Comment by Ingo60** [comment]
There are no such plans.
