### ISSUE TITLE
Using TARGET = 1.7 in the Makefile includes Java8 classes in the jar

### ISSUE THREAD

**Issue by tommay** [Frege/frege#318]
When I set TARGET = 1.7 in the Makefile and build with Java 9 the resulting fregec.jar includes Java8/version 52 class files.

This might not be a big deal but I'm using fregec.jar with an android project, and the proguard and/or the dex creator tools used by the android build choke on Java8/version 52 files.  Fortunately when I remove the frege/run8 directory from fregec.jar all is well and my android project builds and runs.

But it seems like using TARGET = 1.7 should exclude these files automatically.

I'm building from commit 360ba7e394d19ca2a038698250360d3969a04a76.

**Comment by Ingo60** [comment]
Yes, this is indeed so.

We could perhaps do something like

    [ $TARGET$ = 1.7 ] && rm - rf build/frege/run8

before jarring the stuff together.

Please check it out and supply a pull request!

**Comment by tommay** [comment]
Pull request submitted, done in a way that seems more pro-active and less ad hoc.  https://github.com/Frege/frege/pull/319

**Comment by tommay** [comment]
The test in the shell command should really be <= "1.7" not = "1.7" but that's not such an easy test to do.

**Comment by Ingo60** [comment]
We can safely assume that anything below 1.7 is irrelevant, and also not supported anymore.
