### ISSUE TITLE
Porting Vinyl to Frege

### ISSUE THREAD

**Issue by codygman** [Frege/frege#321]
I think having [Vinyl](https://github.com/VinylRecords/Vinyl/) for Frege would be useful. Here are the language pragmas used in Vinyl:

```
{-# LANGUAGE ConstraintKinds       #-}
{-# LANGUAGE DataKinds             #-}
{-# LANGUAGE FlexibleContexts      #-}
{-# LANGUAGE FlexibleInstances     #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE ExplicitNamespaces #-}
{-# LANGUAGE PolyKinds  #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE BangPatterns          #-}
{-# LANGUAGE CPP                   #-}
```

Are there plans to add any of these? Also adding template Frege as discussed in #59 would be necessary to then use Vinyl to make a Frege version of [Frames](https://github.com/acowley/Frames).

**Comment by Ingo60** [comment]
Some of those extensions are supported.
However, crucial ones like DataKinds, ConstraintKinds, PolyKinds and others are not and IMHO it's unlikely they will be supported in the foreseeable future.
