### ISSUE TITLE
Frege on JCenter and Maven still broken.

### ISSUE THREAD

**Issue by russel** [Frege/frege#327]
From what I can see the 3.24.100.1 artefact on JCenter and Maven is still broken. Is there any possibility of this being fixed?

**Comment by talios** [comment]
On 11 Mar 2017, at 23:29, Russel Winder wrote:

> From what I can see the 3.24.100.1 artefact on JCenter and Maven is still broken. Is there any possibility of this being fixed?

Was this one of the ones I deployed to Maven?  I've never deployed to JCenter so unless someone took over?

What's the current problem?

Mark


-- 
Mark Derricutt
http://www.theoryinpractice.net
http://www.chaliceofblood.net
http://plus.google.com/+MarkDerricutt
http://twitter.com/talios
http://facebook.com/mderricutt

**Comment by russel** [comment]
There are 3.23 version on Maven that work. there is a 3.24.100 reported on Maven but it does not work. With the Gradle file:
```
plugins {
  id "org.frege-lang" version "0.8"
}

targetCompatibility = 8
//targetCompatibility = 9

repositories {
  jcenter()
  mavenCentral()
}

dependencies {
  //compile 'org.frege-lang:frege:3.23.+'
  compile 'org.frege-lang:frege:3.24.+'
  //compile files(System.properties['user.home'] + '/lib/JDK/frege.jar')
}

defaultTasks 'test'
```
(sorry about all the bits for experimentation), I get:
```
|> gradle
:compileJava NO-SOURCE
:compileFrege
Error: Could not find or load main class frege.compiler.Main
:compileFrege FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileFrege'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.508 secs
```
which is due to the 3.24.X artefact reported on Maven not actually being a complete deployment in some way shape or form. The local install works fine, but this is not a viable workflow, the artefact on Maven or JCenter ought to do the job. (Apologies for anger levels but this was reported first ages ago and nothing has happened, this is terrible for traction of Frege.)

**Comment by yveszoundi** [comment]
+1

Same as @russel, I think that the inability to provide working jars (Maven/JCenter) can really hurt the project traction, as well as Frege adoption. I felt like Frege was both more mature and a better direction compared to [eta-lang](https://github.com/typelead/eta) (wasted effort IMO): Got the same issues as @russel when running a basic hello world application (Maven and Gradle Frege plugins).

It's "**weird**" not to be able to fix broken artifacts upload, after a while: something might have changed (addition of classifiers, etc.), it's clear that some files are not getting uploaded: https://jcenter.bintray.com/org/frege-lang/frege/3.24.100.1/. IMO, this should be a top priority :-).

In the the future, if possible, I'd recommend try to switch Frege's build system to Maven/Gradle, with the ability to push artifacts directly to Maven/JCenter, _directly from the main Frege project_.

**Comment by Ingo60** [comment]
I'd be happy to upload working JARs to wherever it's best. 
However, I've simply no idea how to do this.

I also ask kindly to open issues regarding build tools in the respective sub-projects.
