### ISSUE TITLE
Haskell !! operator not realised

### ISSUE THREAD

**Issue by russel** [Frege/frege#328]
This version of Fibonacci, which compiles with Haskell fails with Frege;
```
lazyListRecursive :: Integer -> Integer
lazyListRecursive n
    | n < 0 = error exceptionErrorMessage
    | otherwise = fibonacciSequence !! fromInteger n
    where
      fibonacciSequence = fs 0 1
          where
            fs a b = a : fs b (a + b)
```
The error is:
```
can't resolve `!!`, did you mean `!~` perhaps?
```

**Comment by Ingo60** [comment]
See also #242 

You must use a compiler earlier than 3.24.27

**Comment by russel** [comment]
I am using a 3.23 as there is no 3.24 available on Maven or JCenter.

Does this mean the !! is deprecated and being removed?

**Comment by Ingo60** [comment]
Ok, in that case, you'll find it in `Data.List`

    import Data.List (!!)

**Comment by russel** [comment]
Ah, OK so where Haskell doesn't require explicitly importing, Frege does…

**Comment by Ingo60** [comment]
This is exactly the incompatibility we fixed in #242

**Comment by russel** [comment]
No worries now I know. I failed to find that other issue, which is embarrassing for me.

**Comment by russel** [comment]
@Ingo60 You said "You must use a compiler earlier than 3.24.27" but I think you meant "You must be using a compiler earlier than 3.24.27" The difference is actually rather crucial, and explains some of my comments which may have seemed weird to you at the time.

**Comment by Ingo60** [comment]
@russel Yes, that's right, sorry for that. In German, there is no such grammatical difference.

By the way, the other issue was https://github.com/Frege/frege/issues/242

**Comment by russel** [comment]
Interesting that German does not distinguish a command from an observation. :-) But that is for another medium of exchange.

My pressure now has to be to get 3.24.100.1 alive and well on Maven or JCenter – it is not currently.
