### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by treeowl** [Frege/frege#339]
There hasn't been any release since a "preliminary" one in 2016 that came with a claim that another was coming within a few weeks. There have been many hundreds of commits to master since then. Is there a release on the horizon?

**Comment by treeowl** [comment]
Note: I'm one of the maintainers of the `containers` package for Haskell. I was thinking it might be nice to port more of it to Frege, both to support Frege users and to keep us honest about portability claims. But I don't really want to embark on a large project using a badly outdated version of Frege.

**Comment by Ingo60** [comment]
You're right, it's about time.

The delay is caused by 
a) several problems with higher order types (see other issues) 
b) perfectionism, that is, hesitating to release something with known errors
c) lack of time/committers to finally fix everything

**Comment by Ingo60** [comment]
done
