### ISSUE TITLE
No class def found error

### ISSUE THREAD

**Issue by ravinder387** [Frege/frege#396]
module Hello where

main :: IO ()

main = println "Hello World"

PS C:\Users\ravin\Downloads\frege-project> java -Xss1m -jar fregec.jar Hello.fr
calling: javac -cp fregec.jar;. -d . -sourcepath . -encoding UTF-8 ./Hello.java
PS C:\Users\ravin\Downloads\frege-project> java Hello
Error: Unable to initialize main class Hello
Caused by: java.lang.NoClassDefFoundError: frege/prelude/PreludeText$CShow

**Comment by Ingo60** [comment]
The class frege/prelude/PreludeText$CShow is not in your classpath.
Try

java -cp fregec.jar;. Hello

or better yet, read and follow the getting started document.
