### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by eliasvasylenko** [Frege/frege#45]
A short look through the subprojects here show that at least some of this stuff is already built using Maven. Is there any chance that the rest could be wrapped in simple Maven projects and everything pushed to Maven Central?

I'm sure I'm not the only one who would appreciate this! It's a great project.

Cheers,

Eli

ETA: FWIW, in particular I ask about this for the purpose of including the JSR 223 support for Frege scripting in a Java project, as discussed briefly here: https://groups.google.com/forum/?fromgroups=#!topic/frege-programming-language/aBJkJXOnUh4

It seems though that these classes - FregeScriptEngine and FregeScriptEngineFactory - are missing from the latest build of the frege-scripting jar, along with the META-INF/services entry. I guess this isn't the place to ask about that though so I'll ~~read through the rest of that discussion and comment there I suppose~~ I didn't find anything there about it so I'll create an issue in frege-scripting. Just mentioning it here for the sake of completeness in terms of where my inquiry is coming from.

Thanks again.

**Comment by ysb33r** [comment]
Why don't you push to Bintray instead and worry about Maven Central later (Bintray makes it easier to sync to Maven Central anyway).

It will be a lot easier to create an Frege organisation account on Bintray.

**Comment by Ingo60** [comment]
I think this has now been resolved? 
Can someone write a short summary and close it?

**Comment by talios** [comment]
On 28 Feb 2015, at 23:09, Ingo Wechsung wrote:

> I think this has now been resolved?
> Can someone write a short summary and close it?

Finally got around to pushing my frege bundle under the org.frege-lang:frege GAV ( same version of the last release ).

Mark


-- 
Mark Derricutt
http://www.theoryinpractice.net
http://www.chaliceofblood.net
http://plus.google.com/+MarkDerricutt
http://twitter.com/talios
http://facebook.com/mderricutt

**Comment by Ingo60** [comment]
Thank you, Mark.
