### ISSUE TITLE
Latest eclipse plugin requires java 8 -- not documented

### ISSUE THREAD

**Issue by ccozianu** [Frege/frege#98]
Just tried frege on 2015-01-04 via the eclipse plugin.

Out of the box project fails to build and .fr files will not be open with a rather cryptic message -- that  I did not save, but something to the extent that the Monad doesn't support major version minor version '52.0', which led me to believe that I ought to try it with jdk 8, and then it worked.

Pls update the doc or, add the needed javac flag to the build to support JDK 7 so as to avoid users wasting time debugging this condition.

Thx,
Costin

**Comment by Ingo60** [comment]
Hi, 

You are right, I noticed yesterday after uploading it that Eclipse somehow didn't honor my Java Compiler target vm settings.

I can fix this not before next weekend, so you have 2 options:

Use it as it is with Java 8. 

Un install it and install previous version, should be 3.22.92
For this you need to check the appropriate check box in the install dialog to see the older versions. 

Sorry for the inconvenience. 
Regards, Ingo

**Comment by Ingo60** [comment]
Uploaded fregIDE for 3.22.324, this should need JDK7 only.
